"""One-time authorised addition of Twinkle 49; canonical HTML is maintained in content/rooms."""
from pathlib import Path
import json,re,html
R=Path(__file__).resolve().parents[1];D=R/'content/rooms'
slug='ai-pdoom';headline='Odds on a fair go?'
gripe="They\u2019ve got odds on AI wiping us out; what are the odds of it giving us a bloomin\u2019 fair go?"
def read(n):return json.loads((R/n).read_text(encoding='utf-8'))
def write(n,d):(R/n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
copy=read('content/twinkle-reviewed-copy.json');assert len(copy)==48,'Completed migration: do not rerun'
copy.append(dict(number=49,slug=slug,headline=headline,gripe=gripe,destination='ai-pdoom.html'));write('content/twinkle-reviewed-copy.json',copy)
inv=read('content/public-topic-inventory.json');inv['totalTwinkles']=49;inv['newTwinkleOrder'].append(slug);inv['followupTopics'].append(dict(topic='AI p(doom), protopia, fair go and Joyful Responsible Abundance',twinkle='pages/twinkle-ai-pdoom.html',room='pages/ai-pdoom.html'));inv['topicLabels'][slug]='AI p(doom)';write('content/public-topic-inventory.json',inv)
icons=read('content/twinkle-topic-icons.json');icons[slug]='pie-chart';write('content/twinkle-topic-icons.json',icons)
t=read('content/home-ticker.json');t['items'].append(dict(headline='AI p(doom)',scope='AI futures: risk, protopia, fair go and abundance',href='pages/twinkle-ai-pdoom.html',checked='2026-10-04',source='https://safe.ai/work/statement-on-ai-extinction-risk',note='Editorial question about AI outcomes; no consensus probability or measured forecast is asserted.'));t['twinkleCoverage']['count']=49;t['twinkleCoverage']['note']=t['twinkleCoverage']['note'].replace('All 48','All 49');write('content/home-ticker.json',t)
s=(D/'twinkle-political-lies.html').read_text(encoding='utf-8')
for pattern,value in [(r'<title>.*?</title>','<title>'+html.escape(headline)+' | P4A</title>'),(r'<meta name="description" content="[^"]*">','<meta name="description" content="'+html.escape(gripe)+'">'),(r'<h1>.*?</h1>','<h1>'+html.escape(headline)+'</h1>'),(r'<p class="hero-copy">.*?</p>','<p class="hero-copy">'+html.escape(gripe)+'</p>'),(r'<h2>The one-breath drop</h2><p>.*?</p>','<h2>The one-breath drop</h2><p>&ldquo;'+html.escape(gripe)+'&rdquo;</p>')]:s,n=re.subn(pattern,lambda m:value,s,count=1,flags=re.S);assert n==1
s=s.replace('Twinkle 48 / Political lies','Twinkle 49 / AI p(doom)').replace('href="twinkle-super-investments.html">Previous Twinkle 47','href="twinkle-political-lies.html">Previous Twinkle 48').replace('href="truth-engine.html">Follow-through room','href="ai-pdoom.html">Follow-through room');(D/'twinkle-ai-pdoom.html').write_text(s,encoding='utf-8')
for name,a,b in [('twinkle-political-lies.html','href="twinkle-tolls.html">Next Twinkle 01','href="twinkle-ai-pdoom.html">Next Twinkle 49'),('twinkle-tolls.html','href="twinkle-political-lies.html">Previous Twinkle 48','href="twinkle-ai-pdoom.html">Previous Twinkle 49')]:
 p=D/name;s=p.read_text(encoding='utf-8');assert a in s;p.write_text(s.replace(a,b),encoding='utf-8')
p=D/'twinkle.html';s=p.read_text(encoding='utf-8');m=re.search(r'<a class="twinkle-card" href="twinkle-political-lies.html">.*?</a>',s,re.S);assert m
card='<a class="twinkle-card" href="twinkle-ai-pdoom.html"><div class="seed-marker"><span>49</span><img class="seed-icon" src="../assets/topic-icons/pie-chart.svg" width="36" height="36" alt="" loading="lazy"></div><h3>'+html.escape(headline)+'</h3><p>'+html.escape(gripe)+'</p></a>'
s=s[:m.end()]+card+s[m.end():];s=s.replace('Forty-eight Twinkles','Forty-nine Twinkles').replace('forty-four open seeds','forty-five open seeds').replace('Forty-four more connections','Forty-five more connections');p.write_text(s,encoding='utf-8')
p=R/'assets/site-nav.js';s=p.read_text(encoding='utf-8');a="{ href: 'pages/twinkle-political-lies.html', title: 'Twinkle 48: Political lies', note: 'Lying, but authorised.' }";assert a in s;s=s.replace(a,a+",\n        { href: 'pages/twinkle-ai-pdoom.html', title: 'Twinkle 49: AI p(doom)', note: 'Odds on a fair go?' }")
a="{ href: 'pages/super-investments.html', title: 'Super investments', note: 'Holdings, fees, screens and member control.' }";assert a in s;s=s.replace(a,a+",\n        { href: 'pages/ai-pdoom.html', title: 'AI futures', note: 'Doom, protopia, a fair go and joyful responsible abundance.' }");p.write_text(s,encoding='utf-8')
p=R/'README.md';s=p.read_text(encoding='utf-8').replace('now has 48 Twinkles','now has 49 Twinkles').replace('All 48 Twinkle HTML sources','All 49 Twinkle HTML sources');s+='\nTwinkle 49, AI p(doom), opens `pages/ai-pdoom.html`: four outcome questions with dated primary sources and links to the existing GAJRA Earth Claude build. `tools/add-ai-pdoom-twinkle.py` is a completed one-time migration; publish subsequent edits with `build-policy-rooms.py`. Earlier 48 approved entries and historical planning audits remain intact.\n\nEditorial preference: do not use "bloody" or "bloody hell" as colloquialisms in new copy; use "bloomin’" where requested. Preserve unrelated source quotations and previously approved seeds unless an edit is specifically authorised.\n';p.write_text(s,encoding='utf-8')
print('Added Twinkle 49 without replacing the earlier 48')
