"""One-time authorised addition of Twinkle 48; do not rerun."""
from pathlib import Path
import html,json,re
R=Path(__file__).resolve().parents[1];D=R/'content/rooms'
slug='political-lies';headline='Lying, but authorised.'
gripe='They can fit “authorised by” into every election ad; I’d love to see them have a crack at “true”.'
def read(name):return json.loads((R/name).read_text(encoding='utf-8'))
def write(name,data):(R/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
inventory=read('content/public-topic-inventory.json');assert inventory['totalTwinkles']==47
inventory['totalTwinkles']=48;inventory['newTwinkleOrder'].append(slug)
inventory['followupTopics'].append({'topic':'Political lying and advertising truth','twinkle':'pages/twinkle-political-lies.html','room':'pages/truth-engine.html'})
write('content/public-topic-inventory.json',inventory)
copy=read('content/twinkle-reviewed-copy.json');copy.append({'number':48,'slug':slug,'headline':headline,'gripe':gripe,'destination':'truth-engine.html'});write('content/twinkle-reviewed-copy.json',copy)
icons=read('content/twinkle-topic-icons.json');icons[slug]='check-square';write('content/twinkle-topic-icons.json',icons)
ticker=read('content/home-ticker.json');ticker['items'].append({'headline':'Political lies','scope':'Political advertising and truth','href':'pages/twinkle-political-lies.html','checked':'2026-10-03','source':'https://www.aec.gov.au/About_AEC/electoral-communication.htm','note':'Editorial doorway about political claims and advertising; distinct from donations and funding. Authorisation identifies a source, not a truth certification.'});ticker['twinkleCoverage']['count']=48;ticker['twinkleCoverage']['note']=ticker['twinkleCoverage']['note'].replace('All 47','All 48');write('content/home-ticker.json',ticker)
s=(D/'twinkle-super-investments.html').read_text(encoding='utf-8')
for pattern,value in [(r'<title>.*?</title>','<title>'+html.escape(headline)+' | P4A</title>'),(r'<meta name="description" content="[^"]*">','<meta name="description" content="'+html.escape(gripe)+'">'),(r'<h1>.*?</h1>','<h1>'+html.escape(headline)+'</h1>'),(r'<p class="hero-copy">.*?</p>','<p class="hero-copy">'+html.escape(gripe)+'</p>'),(r'<h2>The one-breath drop</h2><p>.*?</p>','<h2>The one-breath drop</h2><p>&ldquo;'+html.escape(gripe)+'&rdquo;</p>')]:s=re.sub(pattern,lambda m:value,s,count=1,flags=re.S)
s=s.replace('Twinkle 47 / Super investments','Twinkle 48 / Political lies').replace('href="twinkle-restricted-plants.html">Previous Twinkle 46','href="twinkle-super-investments.html">Previous Twinkle 47').replace('href="super-investments.html">Follow-through room','href="truth-engine.html">Follow-through room')
(D/'twinkle-political-lies.html').write_text(s,encoding='utf-8')
for name,old,new in [('twinkle-super-investments.html','href="twinkle-tolls.html">Next Twinkle 01','href="twinkle-political-lies.html">Next Twinkle 48'),('twinkle-tolls.html','href="twinkle-super-investments.html">Previous Twinkle 47','href="twinkle-political-lies.html">Previous Twinkle 48')]:
 p=D/name;s=p.read_text(encoding='utf-8');assert old in s;p.write_text(s.replace(old,new),encoding='utf-8')
p=D/'twinkle.html';s=p.read_text(encoding='utf-8');m=re.search(r'<a class="twinkle-card" href="twinkle-super-investments.html">.*?</a>',s,re.S);assert m
card='<a class="twinkle-card" href="twinkle-political-lies.html"><div class="seed-marker"><span>48</span><img class="seed-icon" src="../assets/topic-icons/check-square.svg" width="36" height="36" alt="" loading="lazy"></div><h3>'+html.escape(headline)+'</h3><p>'+html.escape(gripe)+'</p></a>'
s=s[:m.end()]+card+s[m.end():];s=s.replace('Forty-seven Twinkles','Forty-eight Twinkles').replace('forty-three open seeds','forty-four open seeds').replace('Forty-three more connections','Forty-four more connections');p.write_text(s,encoding='utf-8')
p=R/'assets/site-nav.js';s=p.read_text(encoding='utf-8');needle="{ href: 'pages/twinkle-super-investments.html', title: 'Twinkle 47: Super investments', note: 'My super. What is it buying?' }";assert needle in s;s=s.replace(needle,needle+",\n        { href: 'pages/twinkle-political-lies.html', title: 'Twinkle 48: Political lies', note: 'Lying, but authorised.' }");p.write_text(s,encoding='utf-8')
p=D/'truth-engine.html';s=p.read_text(encoding='utf-8');panel='''<div class="feature-panel" id="political-advertising"><p class="eyebrow">Political advertising / checked 3 October 2026</p><h2>Authorised by whom? True according to what?</h2><p>An election ad can affect your vote, your services and your trust in the result. Knowing its source helps, but does not establish that its claims are true. The AEC explains that federal authorisation requirements identify the source of electoral communication; it does not regulate the political content of those communications. This is the federal position described by the AEC, not a claim that every jurisdiction has identical rules.</p><div class="source-links"><a href="https://www.aec.gov.au/About_AEC/electoral-communication.htm">AEC: electoral communication and authorisation</a></div><div class="clue-grid"><div class="clue"><strong>Public evidence and correction ledger</strong><span>Attach sources, dates, disputed interpretations and visible corrections to campaign claims. It is accessible and preserves disagreement, but participation and public attention determine its reach.</span></div><div class="clue"><strong>Independent rapid adjudication</strong><span>A review body could assess disputed factual advertising claims during campaigns. Speed matters, but so do independence, clear jurisdiction, adequate resources and a right to answer.</span></div><div class="clue"><strong>Enforceable truth standard</strong><span>A narrowly defined legal standard could attach consequences to materially false factual advertising. It would need safeguards for opinion, satire, honest mistakes and appeals, and protection against complaints used to silence opponents.</span></div></div><p>These are options for public debate, not an adopted P4A platform. Truth Engine proposes source trails, claim labels and public repairs; Aura Politics explores a candidate mirror with evidence drills, conflicts disclosure and human appeal. Neither is a claim that software can settle political disagreement.</p><p>Save the exact ad, date, platform, authorisation and the specific factual claim. Compare its source with the original document, ask the campaign for evidence or a correction, and publish the response alongside the claim. Use the AEC's authorisation enquiry route for an authorisation issue; a disputed political opinion is a different matter. Ask your representative which truth standard and appeal protections they support.</p><div class="source-links"><a href="twinkle-political-lies.html">Twinkle 48: Political lies</a><a href="aura-politics.html">Aura Politics: the candidate mirror</a><a href="civic-ledger.html">Public record and corrections</a><a href="twinkle-donations.html">Separate question: who funds the ads?</a></div></div>'''
needle='<div class="feature-panel"><p class="eyebrow">Core modules</p>';assert needle in s;s=s.replace(needle,panel+needle,1);p.write_text(s,encoding='utf-8')
p=R/'README.md';s=p.read_text(encoding='utf-8').replace('now has 47 Twinkles','now has 48 Twinkles').replace('All 47 Twinkle HTML sources','All 48 Twinkle HTML sources');s+='\nTwinkle 48, Political lies, adds the approved “Lying, but authorised.” seed without changing the earlier 47 entries. It opens the Truth Engine and remains distinct from Twinkle 17 on donations. The inventory maps this shared destination; `add-political-lies-twinkle.py` is a completed one-time migration.\n';p.write_text(s,encoding='utf-8')
print('Added Twinkle 48 and political advertising follow-through')
