"""Record supplied cross-repository research without modifying visitor pages."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];OUT=R/'docs/planning'
P='https://auraofintelligence.github.io/';G='https://github.com/auraofintelligence/'
sources={}
def add(key,title,repo,path='',kind='Developed proposal or research workbench',file=False):
 sources[key]={'title':title,'url':G+repo+'/blob/main/'+path if file else P+repo+'/'+path,'repository':G+repo,'status':kind}
add('housing','Housing and supported living across different stages of life','multi-site-Minjerribah-network','housing.html','Concrete local collaboration: Luke says he was invited to collaborate with local Indigenous people on Straddie. Not the separate housing-policy work he meant; no public mandate, completed implementation or wider endorsement inferred.')
add('housing-docs','Multi-site working document library','multi-site-Minjerribah-network','documents.html','Supporting-document library')
add('capsules','Straddie Capsule Surge Lab','straddie-capsule-surge-lab')
add('living-twin','Minjerribah Living Twin','minjerribah-living-twin')
add('local-gov','Local government funding inquiry submission','multi-site-Minjerribah-network','source-documents/local-government-funding-inquiry-submission.md','Original submission: public Markdown located by researcher; APH PDF was not retrieved locally',True)
add('wealth','Community wealth funds','moreton-bay-community-wealth-and-mutuals','wealth-funds.html')
add('mutual-care','Mutual Care and Self-Insurance','moreton-bay-community-wealth-and-mutuals','mutual-care.html')
add('country-deals','Country deals','moreton-bay-community-wealth-and-mutuals','country-deals.html')
add('data-sovereignty','Data sovereignty','moreton-bay-community-wealth-and-mutuals','data-sovereignty.html')
add('law2012','Australian Law 2012: Luke’s Relevance','australian-law-2012-lukes-relevance','', 'Public manifest, method and research briefs; original 2012 legal PDFs are not published here')
add('legal-memory','Legal Memory Workbench','legal-memory-workbench','', 'Existing worksheet/Markdown tools; not a deployed legal adjudicator')
sources['legal-engine']={'title':'Australian Legal Engine','url':G+'australian-legal-engine','repository':G+'australian-legal-engine','status':'Actual retrieval code reported by researcher; not run in this local planning audit; source dates still matter'}
add('shared-table','Straddie Shared Table Initiative','shared-table-initiative')
add('ai-kitchen-pdf','AI Kitchen Food Waste Solution','the-great-unveiling','docs/AI%20Kitchen%20Food%20Waste%20Solution.pdf','Supporting PDF: file/title verified, not independently read in full by researcher',True)
add('food-expansion','Integrated Food System AI Expansion','the-great-unveiling','docs/Integrated%20Food%20System%20AI%20Expansion.pdf','Supporting PDF: file/title verified, not independently read in full by researcher',True)
add('mobility','Moreton Bay Autonomous Mobility','moreton-bay-autonomous-mobility','', 'Developed mobility proposal; not an established autonomous passenger/freight service')
add('c-hour-food','C-Hour Food and Wellbeing','C-Hour-introduction','food-and-wellbeing.html')
add('ai-kitchen-original','AI Kitchen Food Waste Solution original','C-Hour-introduction','references/originals/AI_Kitchen_Food_Waste_Solution.md','Original document; any redemption/currency language belongs to the historical version',True)
add('c-hour','C-Hour introduction','C-Hour-introduction','', 'Current nonmonetary contribution framework: money, voluntary contribution and outcomes are separate')
add('c-hour-mechanics','Current C-Hour mechanics','C-Hour-introduction','community-hours.html','Current nonmonetary contribution mechanics')
add('c-hour-pilot','C-Hour twelve-week pilot','C-Hour-introduction','pilot.html','Pilot design; not proof that a funded programme has operated')
add('mutual-futures','Mutual Futures','mutual-futures')
add('capital','Mutual Futures capital calculator','mutual-futures','capital.html','Existing browser calculator reported by researcher; not an acquisition fund or guaranteed-return product')
add('succession','Mutual Futures succession','mutual-futures','succession.html')
add('node','Ready S.E.T. Cultural Intelligence Node','ready-set-co-op-cultural-intelligence-node','', 'Developed node proposal alongside existing public brief tools; not a deployed nationwide rack network')
add('senate','Senate AI and data centres submission, 24 August 2026','multi-site-Minjerribah-network','source-documents/senate-ai-and-data-centres-submission.md','Original submission; alternative public copy identified by researcher',True)
add('eggs','Do Not Put All Our Eggs in One Basket','multi-site-Minjerribah-network','source-documents/do-not-put-all-our-eggs-in-one-basket.md','Original document / developed distributed-capability proposal',True)
add('hardware','Aura Direct Hardware','aura-direct-hardware')
add('energy','Straddie Clean Energy Superpower','straddie-clean-energy-superpower','', 'Dedicated developed energy project with builders; tariffs, capital costs and research concepts need separate treatment')
add('clinical','A Clinical Research and Implementation Plan','multi-site-Minjerribah-network','source-documents/clinical-research-path-aura-of-dementia.md','Original research/implementation proposal, not evidence of clinical efficacy',True)
add('dementia','Aura Dementia','aura-dementia','', 'Developed care/research project; not an approved device or operating clinical service established by this review')
add('healthy-coops','Oceania Healthy De-Slop Co-ops','Oceania-healthy-de-slop-co-ops','', 'Cooperative health/wellbeing proposal; clinical, non-clinical and experimental paths differ')
add('health-business','Project Aura Geode HBOT: cooperative rollout framework','multi-site-Minjerribah-network','source-documents/health-tech-cooperative-business-plan.md','Original business/research proposal; not an approved treatment or funded rollout',True)
add('health-surge','Health Surge and Aura','straddie-capsule-surge-lab','health-surge.html')
add('aged-venture','Aged Care and NDIS venture brief','500-Queens-VC-2026','startup-aged-care-and-ndis.html','Developed venture brief, not a deployed provider or billing system')
add('women-children','Women and children','multi-site-Minjerribah-network','women-children.html','Women-led safe-place proposal, not an operating refuge or selected site')
add('queens','500 Queens Venture Capital','500-Queens-VC-2026','', 'Developed leadership/enterprise work; not completed redistribution or guaranteed funding')
add('ggm','Global Group Marriages','global-group-marriages','', 'Developed household framework and public tools; not a new legal marriage status')
add('matrix','Aura Matrix Studio','aura-matrix-studio','', 'Owner-held context and reflection tools; not an audited identity wallet, fraud detector or clinical treatment')
add('fair-go-ai','A Fair Go for the AI Age','ready-set-co-op-cultural-intelligence-node','supporting-documents/a-fair-go-for-the-ai-age.md','Supporting source located by researcher',True)
add('indigenous-deals','Indigenous Sovereign Resilience','multi-site-Minjerribah-network','source-documents/indigenous-deals-and-sovereign-wealth.md','Original proposal; does not establish authority or agreement for a particular Nation',True)
add('sand','Straddie Sovereign Wealth Fund and Civilisation of Sand','multi-site-Minjerribah-network','source-documents/straddie-sovereign-wealth-fund-civilisation-of-sand.md','Original speculative material/wealth proposal; economics are not established outcomes',True)
add('minerals','Mineral Moonshots','mineral-moonshots','', 'Speculative research and development proposals')
add('kiosks','Straddie Disaster Kiosks','straddie-disaster-kiosks','', 'Developed continuity proposal; not an emergency service or Triple Zero replacement')
add('mesh-pdf','Minjerribah Sovereign Mesh','straddie-disaster-kiosks','docs/Minjerribah_Sovereign_Mesh.pdf','Supporting PDF: file/title verified, not independently read in full by researcher',True)
add('kiosk-pdf','Straddie Disaster Kiosk Pitch','straddie-disaster-kiosks','docs/Straddie_Disaster_Kiosk_Pitch.pdf','Supporting PDF: file/title verified, not independently read in full by researcher',True)
add('aukus','AUKUS Public Inquiry submission, 24 August 2026','multi-site-Minjerribah-network','source-documents/aukus-public-inquiry-submission.md','Original submission; node allowances are planning units, not vendor quotes',True)
add('space-gambit','AUKUS Space Gambit','aukus-space-gambit','', 'Developed strategic thought experiment; distinct capability functions remain distinct')
add('aged-plan','Aura Aged Care','multi-site-Minjerribah-network','source-documents/aged-care-act-adaptation-health-tech-plan.md','Original aged-care adaptation proposal, not provider certification or a fraud-detection system',True)
add('trust-index','AI Trust Index','strange-but-true-ai-trust-index','', 'Trust/evidence project; no operating voice authentication, bank integration or automatic political-truth classifier verified')
add('unga-transcript','Joyful Responsible Abundance / UNGA81 contribution','UNGA81-Luke-Hayes','data/source-transcript.txt','Supporting authored transcript located by researcher',True)
add('ageing','Aged care, longevity and rejuvenation research','multi-site-Minjerribah-network','ageing-longevity.html','Research/proposal page; service accountability is separate from longevity claims')
add('visa','Australian Visa and Activity Atlas','Australian-visa-activity-atlas','', 'Outbound travel/activity-permission reference; not evidence about inward Australian migration settings')
add('vuvale','Fiji Australia Vuvale Union submission','multi-site-Minjerribah-network','source-documents/fiji-australia-vuvale-union-submission.docx','Original DOCX: file/title verified, not independently read in full by researcher',True)
add('peace','Ocean of Peace Alliance submission','multi-site-Minjerribah-network','source-documents/ocean-of-peace-alliance-submission.docx','Original DOCX: file/title verified, not independently read in full by researcher',True)
add('un-love','U.N. of Love','global-group-marriages','un-of-love.html','Marriage-based family-scale thought experiment, not a diplomatic institution')
add('cosmic','Cosmic Nexus','strange-but-true-cosmic-nexus','', 'Creative/research exploration; not proof of an extraordinary physical claim')
add('cosmic-pdf','Cosmic Nexus UAP, AI, AA, R&D','the-great-unveiling','docs/Cosmic%20Nexus%20UAP%2C%20AI%2C%20AA%2C%20R%26D.pdf','Supporting PDF: file/title verified, not independently read in full by researcher',True)
add('micronova','Micronova and Excursions','micronova-and-excursions','', 'Research/extraordinary-hypothesis exploration; claims need their own evidence')
add('club','Community Club Builder: Sandy Sports','community-club-builder-sandy-sports','', 'Community belonging/club-building project; not a mental-health treatment')
add('mental-venture','Mental Health Support venture brief','500-Queens-VC-2026','startup-mental-health-support.html','Bounded non-clinical navigation pilot design with current resources and a named maintenance owner')
add('parlor','Consciousness Parlor','aura-ecosystem','consciousness-parlor.html','Professional-guided psychedelic research/therapy concept; no licensed clinic, approved protocol or efficacy established')
add('parlor-pdf','AURA Consciousness Parlor & GAJRA Earth Encampment blueprint','the-great-unveiling','docs/AURA%20Consciousness%20Parlor%20%26%20GAJRA%20Earth%20Encampment%20%E2%80%93%20Blueprint%20for%20a%20Global%20Consciousness%20Festival%20N.pdf','Supporting PDF: file/title verified, not independently read in full by researcher',True)
add('medicinal-venture','Medicinal Plants and Spices venture brief','500-Queens-VC-2026','startup-medicinal-plants-and-spices.html','Developed adjacent product/research brief; not prohibited-plant law reform or a policy covering all plants')
add('olympic-pilot','Queensland Olympic Earn-to-Heal pilot','multi-site-Minjerribah-network','source-documents/queensland-olympic-earn-to-heal-pilot.pdf','Original PDF: file/title verified, not independently read in full by researcher; no programme approval or Games partnership inferred',True)
add('oceania-surge','Oceania Health and AI Surge Plan','multi-site-Minjerribah-network','source-documents/oceania-health-and-ai-surge-plan.md','Original developed proposal, not funded infrastructure',True)
add('oceania','P4A Oceania cinematic lab','p4a-oceania-cinema','', 'Regional civic and scenario workbench; not a Games partnership')
add('native-nations','Native Nations Sovereign Co-Evolution Lab','p4a-native-nations-cinema','', 'Nation-authored participation and agreement-repair workbench; no cultural authority, consent or endorsement inferred')
add('solar-swarm','Virtual Solar Swarm','virtual-solar-swarm','', 'Observational/research connection; does not establish extraordinary claims or a single forecast across hazard families')
add('mens-recovery','Surf-side men’s alcohol and drug free camp','multi-site-Minjerribah-network','mens-recovery.html','Local recovery/care proposal; not a verified operating PTSD programme')
add('music','Sovereign Music Australia','sovereign-music-australia','', 'Creator-owned records and rights/royalty work; not a complete training-consent market')
add('rights','Rights Engine','sovereign-music-australia','rights.html','Concrete rights/provenance and royalty cases; not a complete licensing market')
add('equality','Designing Equality','500-Queens-VC-2026','designing-equality.html','Developed leadership/equality design; outcomes require their own evaluation')
add('ggm-framework','Global Group Marriages framework','global-group-marriages','framework.html','Authored optional family framework; not current legal recognition of multi-person marriage')
add('ggm-care','Sovereignty and care','global-group-marriages','sovereignty-care.html','Authored personal-sovereignty and shared-care design, not a prescribed household form')
NOTES='''1|local-gov,wealth,law2012,legal-memory|The public Markdown local-government submission supplies an accessible supporting source alongside the locally found APH link. Community wealth adds retained returns.|No operational national toll-contract database verified.|Build one motorway concession/extension/ownership/escalation case with lawful review points.
2|shared-table,ai-kitchen-pdf,food-expansion,mobility,c-hour-food,ai-kitchen-original|Shared Table adds food circles and pantry/freezer/preserving buffers; Garden Mate and AI Kitchen add growing and food-waste planning.|Existing food tools do not establish nationwide bill reductions. Historical redemption wording in original C-Hour documents is not current mechanics.|Model household-to-street-to-freight costs, waste prevented, growing, shared purchasing and delivery.
3|mutual-care,wealth,c-hour|Moreton Bay has dedicated mutual-care and wealth-fund pages; contribution records can describe prevention work.|No operating insurance product or actuarial portfolio is established; current C-Hour is nonmonetary.|Compare three distinct lawful mutual/risk arrangements, with a small-risk example and separate catastrophe exposure.
4|mutual-futures,c-hour,node,capital,succession|Mutual Futures adds an actual capital calculator and succession material to the existing work/rest/skills proposals.|No workforce placement programme or acquisition fund established.|Develop an owner-retirement/sector-switch journey with wages, training, rest and retained local ownership, using the calculator as a transparent tool.
5|housing,housing-docs,capsules,living-twin,c-hour|Multi-site is a relevant concrete local collaboration Luke was invited into with Indigenous people on Straddie; Capsule Surge Lab and Living Twin add adaptation/scenario connections.|Luke confirms Multi-site is not the separate housing-policy work he meant. It is not a generic national framework; no public mandate, implementation or wider endorsement is inferred. Current nonmonetary contribution is not redeemable housing currency.|Keep the existing many-pathway housing room, use the local collaboration only in its actual context, and leave the separate policy source unidentified pending a targeted lead.
6|energy,wealth,hardware|Clean Energy Superpower is a substantial dedicated energy connection, including solar/storage/sharing builders.|Public-assets currently under-serves this material; builders and research concepts do not establish operating energy economics.|Develop a power-specific room or branch using actual tariffs, capital, maintenance and ownership scenarios.
7|clinical,dementia,healthy-coops,health-business,health-surge,aged-venture|The source corpus adds an original clinical implementation plan, cooperative rollout framework, dementia work and care venture brief.|No approved health device, measured appointment saving or operating clinical service established.|Develop access, administration and prevention branches with an evaluation ladder, keeping ordinary care, wellbeing and experimental devices distinct.
8|women-children,housing,legal-memory|Women-led safe-place planning provides a direct authored connection from immediate safety to supported housing.|No refuge service, selected site or commissioned safety pathway established.|Model private exit planning separately from public capacity, including children, pets, income, transport and sustained housing.
9|c-hour,queens,ggm,c-hour-mechanics,c-hour-pilot|Current C-Hour mechanics and twelve-week pilot design, 500 Queens and optional shared family-care arrangements broaden the care proposal.|No dedicated operating childcare service or fee/funding simulator verified. Voluntary contribution is nonmonetary and distinct from professional wages.|Build a care-capacity, roster and cost model that keeps wages, voluntary work and household choices separate.
10|legal-engine,legal-memory|Actual retrieval code and legal-memory tools can support dated tax-to-price receipts.|No dedicated developed beer-tax proposal found beyond the existing P4A room.|Develop the schooner price decomposition with venue inputs, duty dates and measured pass-through.
11|node,senate,eggs,hardware|Two additional original-document paths support federated compute, public benefit and vendor portability.|Nodes and public allocation terms remain proposals rather than installed nationwide infrastructure.|Use the submissions as the backbone of an explicit operating/budget comparison of power, water, jobs and compute commitments.
12|data-sovereignty,matrix,hardware,legal-memory,fair-go-ai|Owner-held context, narrow permissions and local processing now have direct data-sovereignty, Matrix Studio and Fair Go source connections.|These tools are not a complete identity wallet, audited security system or breach-remediation service.|Work through one licence-verification case, separating existing storage/export from proposed credential, revocation and recovery mechanisms.
13|country-deals,indigenous-deals,sand,minerals|The source documents develop community equity, retained productive capability and intergenerational funds, including Country-led deals.|Speculative sand/material economics and Native Title authority are not already settled.|Compare royalties, equity, processing, rehabilitation, terms and community returns in a sourced resource-deal model.
14|kiosks,mesh-pdf,kiosk-pdf,node|Disaster Kiosks and the two named PDFs supply a much closer continuity proposal than generic data sovereignty alone.|Kiosks are not an operating emergency service and cannot promise a Triple Zero replacement.|Build an outage dependency map and testable power/comms plan with emergency-authority interfaces explicit.
15|aukus,space-gambit,hardware|A dedicated AUKUS inquiry submission and Space Gambit add opportunity-cost comparisons with civilian intelligence, education, disaster resilience and scientific cooperation.|The A$6m node allowance is a planning unit, not a vendor quote; distinct strategic functions must remain distinct.|Put the authored 32-site, 100-site and global scenarios beside defence costs, delivery and dependency assumptions; keep the ISS gambit a separate thought experiment.
16|legal-memory,law2012,legal-engine|Conflict-of-interest registers, cooling-off time and source-linked institutional memory connect the existing ledger direction to legal tools.|No operational revolving-door register verified.|Model one public official, portfolio and subsequent-employer chain with source dates, applicable rules, response/correction and a cooling-off clock.
17|unga-transcript,legal-memory,legal-engine,c-hour|The UNGA81 source adds near-transfer-speed public donation receipts, lawful disclosure, conflicts and correction trails.|No live political donation ingestion/disclosure system established. Current C-Hour remains nonmonetary.|Develop a donation-specific schema and mock example separating political money, ordinary paid services and verified voluntary time.
18|olympic-pilot,oceania-surge,capsules,oceania|Original Olympic and Oceania surge proposals connect Games-scale mobilisation to enduring health, skills, compute and local infrastructure, with capsule surge capacity.|No programme approval, Games partnership or funded infrastructure implied. The Earn-to-Heal PDF was file/title verified; historical contribution/reward wording needs reconciliation with current nonmonetary C-Hour.|Create 2032 and 2050 legacy scenarios comparing temporary beds with stable housing, retained assets, operator skills, maintenance and everyday community use.
19|native-nations,country-deals,indigenous-deals|Treaty Atlas and kintsugi agreement repair connect nation-authored participation with Indigenous data authority and equity/wealth research.|Generic international comparisons do not settle Australian treaty scope or confer cultural authority.|Give the existing room separate record/proposal layers and agreement-specific history, parties, authority, obligations and repair options.
20|cosmic,cosmic-pdf,solar-swarm|Cosmic Nexus source, hypothesis and fieldwork lanes add to Truth Engine provenance, public assessment and correction.|Neither the site nor the source document establishes an extraordinary claim as true; the PDF was file/title verified.|Build one claim dossier with observations, instruments, chain of custody, competing hypotheses and evidence that would change confidence.
21|micronova,mutual-care,living-twin,solar-swarm|Deep time is the climate-change topic. Long-term risk, community prevention and observational capability connect to the current flood example.|The flood-focused material currently covers only part of the climate-change subject. Micronova hypotheses are a separate research connection, not a replacement climate explanation or the topic definition.|Restore the climate-change framing while retaining flooding as an example; keep distinct hazard families, evidence levels and timescales separate and identify the wider topic gap before any further room development.
22|matrix,clinical,health-surge,mens-recovery|Owner-held context and supported intake connect reduced form burden with practical rest, recovery, care and community infrastructure.|Dementia planning is not PTSD treatment evidence; no dedicated operating PTSD programme verified.|Develop a veteran/first-responder journey with repeated-story burden, access delays, trusted support and validated care outcomes; keep optional research branches distinct.
23|music,rights,trust-index,eggs,fair-go-ai|Sovereign Music adds creator-owned making records, rights provenance, distributor terms and concrete rights/royalty cases.|A complete training-consent/licensing market is not demonstrated.|Develop creator permission and contribution records plus licensing choices using the music cases and cited legal questions about human/AI contribution.
24|trust-index,matrix|Personal sovereignty and transparent AI terms provide foundations, but child-specific safety needs its own design.|No dedicated public child-chatbot safety product/proposal verified in these external projects; Aura Toy is unrelated matrix UI. The local child-safety room already exists.|Deepen that room with age-appropriate interactions, guardian/child rights, memory/data boundaries, escalation and independent testing supported by specialist evidence.
25|data-sovereignty,trust-index,unga-transcript,legal-memory|Owner-controlled boundaries, traceable platform/AI terms and public correction methods strengthen the existing accountability direction.|No operational anti-harassment/moderation system or tested reporting workflow verified.|Build abuse-reporting and remedy pathways with consent, evidence handling, response times and appeals, keeping platform obligations and personal tools distinct.
26|queens,c-hour,mutual-futures,equality,c-hour-mechanics|500 Queens executive leadership and investment influence connect paid-work protection with recognition of unpaid care.|Hourly pay, career progression, care load, ownership and lifetime wealth are separate intervention targets; C-Hour recognition is nonmonetary.|Make those levers visible separately, connect actual venture/leadership pathways and build an illustrative lifetime income/time model.
27|native-nations,country-deals,indigenous-deals,node|Country-led agreement repair connects Indigenous data/compute authority with community ownership and wealth pathways.|No Indigenous consent, endorsement or outcome improvement follows from a proposal.|Develop a nation-chosen outcome/decision-rights case that distinguishes official indicators, community priorities and optional proposals.
28|club,mutual-futures,housing,c-hour|Belonging, skills, sport, maker/media work and supported family stability are developed prevention ingredients; Multi-site remains a local collaboration example only.|No evaluated youth-crime reduction programme verified; club activity alone is not demonstrated to solve crime.|Develop a specific prevention/restoration pathway with victims’ needs, youth needs, service responsibility and measurable safety outcomes.
29|ggm,queens,c-hour,mutual-futures,housing,ggm-framework,ggm-care|Housing security, shared care, adequate income and expanded family frameworks offer different ways to lower barriers to wanted families.|Authored family thought experiments remain optional, not a prescribed moral answer; Multi-site is the clarified local example, not the missing national housing-policy source.|Compare household choices, time, care, housing and autonomy using the authored framework alongside conventional arrangements.
30|ggm,un-love,legal-memory,law2012,ggm-framework,ggm-care|The household framework separates relationship structure, pooled resources, personal sovereignty, mediation and realistic exits, with legal-memory tools for clear agreements.|Global Group Marriages is an authored framework, not current recognition of multi-person marriage.|Develop the existing room through joining, care, resources, disagreement, leaving and ongoing responsibilities, separating law from proposed change.
31|housing,mutual-futures,legal-engine|Housing access can be compared with retirement security in a portfolio including co-ops, land trusts and public-interest leases; Multi-site supplies only a local collaboration example.|No specific super-withdrawal financial model or endorsed recommendation verified.|Add price-response and lifetime-balance comparisons, including people without super or deposits, with fund rules/current law sourced.
32|mutual-futures,wealth,queens,c-hour,capital,succession|Mutual succession, learning from retiring owners, community wealth and women’s investment influence have concrete calculator and succession connections.|These are proposals/tools, not completed redistribution or guaranteed returns. Current C-Hour records nonmonetary contribution.|Model ownership transfer, debt, wages, reserves, dividends and care/time effects, preserving both business competence and broad participation questions.
33|legal-engine,legal-memory,local-gov|Legal retrieval and beneficial-control/contract transparency are useful foundations for examining multinational tax.|No dedicated multinational-tax dataset or developed reform verified.|Build revenue-to-profit-to-tax-to-jurisdiction evidence without inventing an adopted Luke tax policy.
34|clinical,aged-plan,legal-memory,aged-venture|The clinical/Aura Place/access planning split and aged-care corpus add consent-aware support/delivery evidence.|No deployed NDIS fraud detector or validated billing system verified.|Model commissioned and delivered support, invoice, participant confirmation, exceptions and appeal.
35|trust-index,data-sovereignty,legal-memory,unga-transcript,fair-go-ai|AI Trust Index, the UNGA81 transcript and Fair Go document strengthen the provenance and independent-verification direction.|No operating anti-scam detector, voice-authentication service or bank integration verified.|Develop a scam-specific verification/recovery workflow and distinguish detection from known-person verification and payment reversibility.
36|aged-plan,dementia,legal-memory,ageing,aged-venture|The aged-care adaptation source and venture brief add provider/accountability planning and owner-controlled evidence.|These proposals do not certify providers or detect scams; longevity research is a separate branch.|Develop an accessible service-to-authorised-person-to-delivery-to-invoice trail with review and correction.
37|unga-transcript,legal-memory,legal-engine|Truthfulness/advertising and personal data control are adjacent foundations.|Research found grant references, not a developed gambling-harm solution. The dedicated local P4A room already exists.|Deepen that existing room with gambling-specific evidence on advertising, product friction, exclusion, care and revenue conflicts.
38|mobility,shared-table,energy,legal-engine|Coordinated passenger/delivery mobility, food buffers and energy work supply authored alternatives to fuel dependence.|Autonomous services remain proposals; route-specific economics are unresolved.|Model one commute and island freight basket, separating tax, crude price, retail margin and actual travel demand.
39|legal-engine,legal-memory,healthy-coops|Legal tools and accessible cooperative care are adjacent foundations for transparent tax/harm accounting.|No dedicated tobacco-tax policy or cessation programme verified. The local tobacco room already exists.|Deepen the existing room's incidence, illicit-supply and outcome comparisons; experimental wellbeing is not a substitute for cessation care.
40|living-twin,housing,mutual-futures,visa,vuvale|Housing, skills, transport, supported care and regional cooperation can inform the capacity model.|The outbound Visa and Activity Atlas is a permission-model precedent, not evidence about inward migration settings.|Separate students, workers, families and refugees and model local capacity/time lags using current Australian data.
41|aukus,peace,unga-transcript,un-love|Dedicated AUKUS, Ocean of Peace and UNGA81 sources add authored positive-sum security and regional cooperation ideas.|U.N. of Love is a marriage-based family-scale thought experiment, not a diplomatic institution.|Use conflict-specific objectives, civilian consequences, alternatives, dependencies, exit and opportunity-cost tests while preserving the peace proposals.
42|aukus,eggs,node,kiosks|The source cluster makes the case for distributed capability across compute, energy, communications and skills.|Decentralisation is not a security guarantee; standards and maintenance are also dependencies.|Build a failure/dependency test with downtime, vendor exit, recovery, redundancy costs and everyday/severe-shock benefits.
43|cosmic,cosmic-pdf,micronova|Cosmic Nexus and the named original research PDF broaden the existing creative and inquiry pathway.|The records do not establish alien construction or displace known human achievement; the PDF was file/title verified.|Develop a specific chronology/tools/archaeology/evidence dossier with testable alternatives and cultural context.
44|matrix,healthy-coops,club,housing,mutual-futures,mental-venture|Community Club Builder and the bounded 500 Queens non-clinical navigation pilot add belonging and practical access pathways.|Reflection/navigation tools are non-clinical; no mental-health treatment effect is established.|Develop continuity of care separately from community support/research, measuring intake burden, access and user-valued outcomes with a named resource-maintenance owner.
45|parlor,parlor-pdf,healthy-coops,legal-memory|Consciousness Parlor is an existing professional-guided research/therapy concept with a named blueprint.|No licensed clinic, approved protocol, efficacy or affordable delivery model verified.|Deepen the existing psychedelic room using condition-specific evidence, regulation, access costs, preparation and follow-up while retaining the authored concept.
46|law2012,legal-engine,legal-memory,parlor,medicinal-venture|Luke's Relevance Ladder/change-the-law method and the medicinal-plants venture brief add concrete authored connections.|The adjacent venture does not establish prohibited-plant reform or one policy for all plants.|Separate species, substance, use and jurisdiction, then compare possession, cultivation, clinical research, ecology and harm claims.
47|mutual-futures,wealth,legal-memory,legal-engine|Ownership and public-interest money-flow models can inform readable super disclosures.|No live holdings ingestion, look-through exposure model or fund recommendation verified; mutual succession is not necessarily a suitable super investment.|Build a statement-to-holdings drill-down with dated fees, exposures, voting and member options.
48|unga-transcript,legal-engine,law2012,trust-index|The UNGA81 truthfulness/de-slop sources add authored depth to the local Truth Engine and Aura Politics link.|No national political-ad tribunal or automatic truth classifier verified.|Develop claim-to-evidence-to-funding-to-correction records, keeping satire, opinion, mistake and deliberate deception distinguishable.'''
topics={}
for line in NOTES.splitlines():
 n,refs,contribution,stage,nextwork=line.split('|')
 assert all(k in sources for k in refs.split(','))
 topics[n]={'sourceKeys':refs.split(','),'additionalSubstance':contribution,'stageAndGap':stage,'proposedNextWork':nextwork}
data={'received':'2026-10-03','provenance':'Cross-repository researcher report supplied in the parent task; not an independent re-audit of every external file by the local editor.','publicCatalogueReported':168,'readmesRetrievedReported':166,'missingTransferredTopicSections':[],'partiallyTransferredTopicSections':[],'currentCHour':'Current C-Hour is nonmonetary: money, voluntary contribution and outcomes are separate. Redeemable-token/currency wording in older originals is history and requires version reconciliation before reuse.','housingLocalExample':{'url':sources['housing']['url'],'repository':sources['housing']['repository'],'documents':sources['housing-docs']['url'],'status':'Luke clarified that this is NOT the separate housing-policy work he meant. It is an actual local plan he was invited to collaborate on with Indigenous people on Straddie. Relevant local example only; no public mandate, completed implementation or wider endorsement inferred. Separate housing-policy source remains unidentified; wait for a targeted lead rather than broad searching.'},'sources':sources,'topics':topics}
(OUT/'cross-repo-evidence-2026-10-03.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Recorded',len(sources),'cross-repository sources for',len(topics),'received topic sections; missing sections explicitly recorded')
