"""One-time second expansion. Canonical editable HTML lives in content/rooms."""
from pathlib import Path
import re,json,html
R=Path(__file__).resolve().parents[1];D=R/'content/rooms'
def p(t):return '<p>'+t+'</p>'
def links(items):return '<div class="source-links">'+''.join(f'<a href="{u}">{t}</a>' for u,t in items)+'</div>'
def panel(t,b,id=''):return '<div class="feature-panel"'+(f' id="{id}"' if id else '')+'><h2>'+t+'</h2>'+b+'</div>'
def opts(items):return '<div class="clue-grid">'+''.join(f'<div class="clue"><strong>{t}</strong><span>{b}</span></div>' for t,b in items)+'</div>'
template=(D/'ai-copyright.html').read_text(encoding='utf-8');head=template[:template.index('  <main')];foot=template[template.index('  <footer'):]
def page(title,sub,body,eyebrow='Public choices / October 2026'):
 h=re.sub(r'<title>.*?</title>',f'<title>{html.escape(title)} | P4A</title>',head)
 h=re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{html.escape(sub,quote=True)}">',h)
 return h+f'<main id="main"><section class="hero page-hero"><div class="hero-image"><img src="../assets/purple-festival.webp" alt="" fetchpriority="high"></div><div class="hero-content reveal"><p class="eyebrow">{eyebrow}</p><h1>{title}</h1><p class="hero-copy">{sub}</p><div class="hero-actions"><a class="button button-primary" href="#room">Open the room</a><a class="button button-secondary" href="twinkle.html#seeds">All Twinkles</a></div></div></section><section class="section" id="room"><div class="page-copy reveal">'+body+'</div></section></main>\n'+foot
def save(slug,s):(D/f'{slug}.html').write_text(s,encoding='utf-8')
def append(slug,b):
 f=D/f'{slug}.html';s=f.read_text(encoding='utf-8') if f.exists() else (R/'pages'/f'{slug}.html').read_text(encoding='utf-8')
 if '<div class="next-trail">' in s:s=s.replace('<div class="next-trail">',b+'<div class="next-trail">',1)
 else:s=s.replace('</main>','<section class="section"><div class="page-copy">'+b+'</div></section></main>',1)
 save(slug,s)
mutual='https://auraofintelligence.github.io/mutual-futures/'
ggm='https://auraofintelligence.github.io/global-group-marriages/'
cap='https://auraofintelligence.github.io/UNGA81-Luke-Hayes/capability.html'
tga='https://www.tga.gov.au/products/unapproved-therapeutic-goods/mdma-and-psilocybine/access-pathways/prescribe-mdma-or-psilocybine-psychiatrists'
topics=[]
def topic(slug,label,title,sub,facts,sources,choices,action,connection,related,drop,icon):
 topics.append(dict(slug=slug,label=label,title=title,sub=sub,facts=facts,sources=sources,choices=choices,action=action,connection=connection,related=related,drop=drop,icon=icon))
topic('gender-pay-gap','Gender pay gap','Same ambition. Different pay packet.',
'Pay, promotion, caring time and the value of work belong in the same conversation. A national gap and unequal pay for the same job are different questions.',
'WGEA’s 2024-25 private-sector total-remuneration average gender pay gap is 21.1%. This measure includes more than base salary and uses annualised full-time-equivalent pay. It does not mean every woman receives 21.1% less than a man doing the identical job. Mean, median, industry and employer measures answer different questions; compare the same measure over time.',
[('https://www.wgea.gov.au/pay-and-gender/gender-pay-gap-data','WGEA: measures and employer data')],
[('Pay transparency and job evaluation','Published ranges and consistent evaluation can reveal unjustified differences. Organisations need a correction process and protection against retaliation, while respecting personal salary information.'),('Progression and caring-compatible work','Predictable hours, usable parental leave for all parents and promotion access can widen opportunity. Flexible arrangements fail if the career penalty simply moves out of view.'),('Value care work and build leadership routes','Review pay, skills and advancement in care-heavy sectors and support women’s enterprise. Funding and workforce implications need an explicit public receipt.')],
'Look up your employer in WGEA’s explorer, read its explanation and ask about its action plan. Through a union, staff forum or representative, ask for comparable-role audits, promotion outcomes and leave take-up. Do not infer individual discrimination from one aggregate number.',
'Mutual Futures connects shared productive ownership with women’s leadership through 500 Queens and recognition of voluntary care through C-Hours. Those proposals invite practical questions about who controls capital and who gets time to learn; care recognition should not replace paid work.',
[(mutual,'Read Mutual Futures and its leadership connections'),('workforce-transition.html','Paid learning and work-life choices'),('marriage-divorce.html','Sharing care in families')],
'Publish the gap, explain the pathway, show what changed.','bar-chart-2')
topic('closing-the-gap','Closing the Gap','Another target. Who holds the power?',
'First Nations-led decisions, community-controlled services and accountable funding belong beside the outcome measures. The numbers should help communities exercise authority.',
'The Productivity Commission’s July 2026 dashboard marks the preschool-enrolment target as met. It also reports 33.9% of children commencing school developmentally on track in 2024 and 81.4% living in appropriately sized housing in 2021. These are different populations, measures and years; progress in one does not settle the others. The Coalition of Peaks places shared decision-making and stronger community control at the centre of reform.',
[('https://www.pc.gov.au/closing-the-gap-data/dashboard/','July 2026 dashboard and measure definitions'),('https://www.coalitionofpeaks.org.au/','Coalition of Peaks: First Nations-led priorities')],
[('Transfer authority with sustainable funding','Community-controlled organisations can set priorities and build continuity. Governments must relinquish real decision power, fund capacity and agree accountability rather than transfer risk alone.'),('Reform mainstream services','Health, housing, education and justice agencies should change discriminatory practices and report outcomes. Training without authority, budgets and consequences can become another process measure.'),('Community-governed data','Local access and agreed interpretation can make evidence useful. Privacy, collective authority and small-population identification need safeguards; a national dashboard does not replace local knowledge.')],
'Begin with the relevant community-controlled organisation’s published priorities and invitation to participate. Ask government which decision, budget and outcome changed under each Priority Reform. The 2026 review lists a 26 October 2026 submission deadline: check its current status before submitting. Communities choose what information they share.',
'Treaty Atlas offers a place to examine agreements and obligations, while the Sovereignty Stack and Ready S.E.T. proposal separate collective cultural authority from technical access. They are tools for accountable relationships, not a substitute for First Nations leadership.',
[('https://www.pc.gov.au/inquiries-and-research/closing-the-gap-review-2026/','Review and participation status'),('treaty-atlas.html','Existing Treaty Atlas'),('sovereignty-stack.html','Data authority and custody')],
'If the target is shared, the decision-making has to be shared too.','sun')
topic('youth-crime','Youth crime','Safe tonight. Fewer victims tomorrow.',
'Victims need support now. Preventing the next offence means examining serious harm, repeat offending and what actually changes a young person’s path.',
'ABS Recorded Crime - Offenders counts alleged offenders proceeded against by police, not convictions or every offence committed. AIHW youth-justice data describe supervision and detention, another population again. Read local offence types, rates, ages and repeat patterns alongside national trends; neither a viral incident nor one national total describes every community.',
[('https://www.abs.gov.au/statistics/people/crime-and-justice/recorded-crime-offenders/2024-25','ABS: alleged-offender measures'),('https://www.aihw.gov.au/reports/youth-justice/youth-justice-in-australia-2024-25','AIHW: youth justice 2024-25')],
[('Victim support and focused enforcement','Fast support, investigation and proportionate responses can address immediate harm. A larger arrest total alone does not demonstrate fewer future victims.'),('Early intervention and stable pathways','School engagement, family support, disability assessment, housing and meaningful work can address underlying needs. Programmes require skilled staff, sustained funding and measured outcomes.'),('Bail support, diversion and rehabilitation','Safe accommodation and supervised alternatives can interrupt repeat offending where appropriate. Serious risk still needs a lawful response; evaluate reoffending and victim outcomes rather than slogans about toughness.')],
'Ask state representatives for local serious-offence, repeat-offending and victim-support measures with comparable dates. Ask funded programmes to report completion, reoffending and wellbeing outcomes. Use official victim-support and police routes for individual incidents; do not publish identifying allegations about children.',
'workforce-transition and Ready S.E.T. learning proposals offer practical pathways to explore alongside youth services. A workshop or paid placement needs safeguarding and professional partners; it is not a claim to replace the justice system.',
[('workforce-transition.html','Learning and paid pathways'),('child-safety.html','Safeguards around young people'),('closing-the-gap.html','Community-led justice context')],
'Count fewer victims, not just louder promises.','navigation')
topic('psychedelic-mental-health','Psychedelic care','Promising treatment. Who can reach it?',
'Psychedelic-assisted care raises questions about evidence, access, cost, supervision and the kind of support that surrounds a medicine.',
'TGA’s authorised-prescriber pathway permits specifically authorised psychiatrists to access MDMA for PTSD and psilocybine for treatment-resistant depression. These remain unapproved medicines, rather than products evaluated and entered on the ARTG through the ordinary approval pathway. Permission under this pathway is not general legalisation or a take-home treatment entitlement.',
[(tga,'TGA: psychiatrist pathway and obligations'),('https://www.tga.gov.au/products/unapproved-therapeutic-goods/mdma-and-psilocybine/access-pathways/access-mdma-or-psilocybine-consumers','TGA: consumer access'),('https://www.ranzcp.org/clinical-guidelines-publications/clinical-guidelines-publications-library/therapeutic-use-of-mdma-for-ptsd-and-psilocybin-for-treatment-resistant-depression','RANZCP: clinical evidence and guidance')],
[('Supervised access with outcome reporting','A regulated pathway can offer access for selected patients while recording benefit and harm. Cost, workforce and selection criteria can leave access unequal.'),('Public-interest research and training','Independent trials, longer follow-up and supervised practitioner training can clarify who benefits and under what conditions. More evidence takes time and should include negative findings.'),('Equitable funding and continuity','Evaluate funding alongside existing effective care, preparation and follow-up. Public resources need comparative benefit, patient choice and protection against exaggerated marketing.')],
'Patients can discuss the official pathway with a qualified treating professional. For policy, ask health representatives about independent evaluation, affordability, consent, practitioner training and reporting. Personal suitability cannot be determined by a campaign page. Treatment access and plant-law reform are separate decisions.',
'Aura Clinical Path provides a connection to care navigation and reduced administrative burden. The broader mental-health room keeps housing, peers, ongoing care and workforce in view so a promising intervention does not become the whole system.',
[('aura-clinical-path.html','Aura Clinical Path'),('mental-health.html','Wider mental health'),('restricted-plants.html','Separate plant and fungi reform debate')],
'Give the promise a fair trial, and people a fair path to care.','aperture')
topic('restricted-plants','Plant prohibition','Rethinking restricted plants and fungi',
'What should adults be free to grow, possess or use, and which safeguards belong around medicine, commerce and public health? Different plants and fungi deserve specific arguments.',
'Personal use does not automatically exempt tobacco cultivation from licensing. ACT cannabis rules contain narrow exceptions to criminal liability and do not amount to national legalisation. Medical access to psilocybine or MDMA does not authorise personal cultivation or production. Each jurisdiction, substance and activity needs its own legal check; a reform proposal is not permission under current law.',
[('https://www.ato.gov.au/law/view/document?LocID=%22SAV%2FTOBACCO%2FFTFNREF74%22','ATO: tobacco licensing guidance'),('https://police.act.gov.au/community-safety/alcohol-and-drugs/drugs-and-the-law','ACT Policing: current distinctions'),('https://www.health.nsw.gov.au/pharmaceutical/Pages/psilocybine-and-mdma.aspx','NSW: controlled medical access')],
[('Reclassification and proportionate penalties','Review whether existing categories and penalties fit the evidence of harm. Reduced penalties are different from legal supply, cultivation rights or medical approval.'),('Bounded adult personal-cultivation reform','Debate a lawful non-commercial pathway with age, location, household and third-party protections. Autonomy and affordability gains must be weighed against access by children, product uncertainty and enforcement design.'),('Regulated supply and medicinal access','Licensed products or supervised services can support quality control and traceability. Compliance costs can exclude people, and commercial promotion may undermine public-health goals.')],
'Put a substance-specific proposal to state and federal representatives: which activity changes, for which adults, with which protections and how will outcomes be measured? Compare access, health harms, enforcement burden, equity and autonomy. This room offers policy choices and legal sources, not growing or production instructions.',
'self-sovereignty and legal-memory ideas provide a way to distinguish personal choice, shared consequences and actual law. The Law Engine can help locate source provisions; human legal review remains essential before acting.',
[('legal-rag.html','Law Engine'),('sovereignty-stack.html','Self-sovereignty and shared responsibilities'),('tobacco.html','Separate Tobacco tax room'),('psychedelic-mental-health.html','Separate supervised-care room')],
'Name the plant, name the harm, then justify the rule.','feather')
topic('ndis-scams','NDIS scams','The support was billed. Was it delivered?',
'Protect disability support from theft without turning every participant’s life into an audit. Fair enforcement and continuity of care must work together.',
'NDIA distinguishes deliberate fraud from mistakes and non-compliance. Its public guidance covers misleading claims and misuse of funds; invoices, service agreements and dates can help investigators assess a concern. An undelivered or duplicated service claim needs checking, but a billing dispute or unfamiliar disability support is not automatically fraud.',
[('https://www.ndis.gov.au/participants/working-providers/protecting-yourself/what-fraud','NDIA: what fraud means'),('https://www.ndis.gov.au/contact/reporting-fraud/how-report-fraud','NDIA: reporting and review routes')],
[('Participant-readable statements','Clear descriptions, dates and accessible verification can expose wrong charges early. Participants should not have to become accountants or lose service when they ask a question.'),('Targeted audits and provider accountability','Investigate suspicious patterns and preserve evidence with due process. Blanket freezes can punish legitimate participants; continuity and review need to be designed in.'),('Independent advocacy and supported decisions','An independent advocate can help challenge pressure, conflicts or identity misuse. Advice must respect the participant’s choices and be funded beyond a crisis.')],
'Keep records privately and report suspected fraud through NDIA’s official form or 1800 650 717. Quality and safety concerns go to the NDIS Quality and Safeguards Commission. Explain what you observed and distinguish suspicion from proof. Ask representatives how enforcement preserves support while recovering improper payments.',
'Civic Ledger can inspire clear service receipts and accountable public spending, with private participant records kept out of public view. The Sovereignty Stack adds purpose limits, access records and correction rights.',
[('civic-ledger.html','Receipts and public accountability'),('sovereignty-stack.html','Private records and permission'),('https://www.ndiscommission.gov.au/','NDIS Commission')],
'Follow the money without putting the person on trial.','check-square')
topic('ai-scams','AI scams','It sounded like someone you trust.',
'A familiar voice, polished document or convincing video can be manufactured. The response needs safer platforms and payments as well as a chance to stop and check.',
'Scamwatch describes AI-enabled impersonation, voice cloning, false endorsements, fake sites and personalised messages. Visual polish or a matching voice does not establish identity. Verification through an independently found official number or a known contact is more useful than trying to spot every visual flaw.',
[('https://www.scamwatch.gov.au/stop-check-protect/help-to-spot-and-avoid-scams/how-scammers-use-technology-and-ai','Scamwatch: AI and impersonation')],
[('Platform and advertiser accountability','Verified advertisers, faster takedowns and repeat-offender controls can interrupt distribution. Appeals and transparent error reporting are needed when legitimate speech or businesses are caught.'),('Payment checks and accessible disputes','Better warnings, trusted-contact options and recovery processes can reduce losses. Delays and false positives have costs; no page should promise automatic reimbursement.'),('Practical verification and support','Teach independent callback and trusted-source checks without blaming victims. Public education cannot carry the entire burden of sophisticated organised fraud.')],
'If money or account details are at risk, contact your bank through its official route promptly. Use Scamwatch to report and follow its recovery guidance. Keep evidence privately and beware of a second scam promising to recover funds for a fee. For policy, ask who must prevent, respond and resolve disputes across the platform-telecom-payment chain.',
'Truth Engine and Sovereignty Stack connect provenance with control over personal information. Signed records and local custody can help a workflow, but no badge or AI detector should be presented as an infallible truth test.',
[('truth-engine.html','Trace the claim and the source'),('sovereignty-stack.html','Reduce unnecessary data exposure'),('online-safety.html','Platform design and redress')],
'Don’t trust the voice. Check the person through a different door.','mic')
topic('aged-care-scams','Aged-care scams','Care should come with a clear receipt.',
'Impersonation, financial coercion, billing fraud and poor service need different responses. Older people retain a voice in every response.',
'My Aged Care warns about scams targeting older people and offers an official complaints route. A caller pretending to assess eligibility is different from a provider charging for an undelivered service, and both differ from coercive control of someone’s money. Suspicion should be documented and assessed; it is not a verdict on all care providers.',
[('https://www.myagedcare.gov.au/news-and-updates/beware-scams-targeting-older-people','My Aged Care: scam warning'),('https://www.myagedcare.gov.au/making-a-complaint','My Aged Care: complaints'),('https://www.agedcarequality.gov.au/older-australians/safety-care/serious-incidents','Commission: serious incidents')],
[('Verify identity and make bills readable','Independent callback routes and itemised statements help people check what happened. Accessible formats, translation and trusted support are essential.'),('Investigate providers and protect continuity','Targeted audits and incident reporting can identify misconduct. A complaint should not leave a person without care or allow an allegation to replace fair investigation.'),('Independent advocacy and supported decisions','Provide help chosen by the older person, including outside the family. Automatic family control can itself undermine autonomy or conceal coercion.')],
'Verify an unexpected caller through the official My Aged Care website or your known provider number. For money lost, contact the bank promptly; for care concerns use My Aged Care or the Commission’s complaint pathway. Ask how you can complain safely and keep services running. In immediate danger call 000.',
'care and C-Hour ideas explore visible contribution and continuity, while the Civic Ledger asks for traceable public value. Personal care records stay private; a public ledger should show programme accountability rather than intimate details.',
[(mutual,'Mutual Futures care and contribution'),('civic-ledger.html','Public receipts'),('mental-health.html','Care continuity')],
'Let the person see the bill, choose the help and keep their voice.','user-check')
topic('gambling-harm','Gambling harm','The app keeps playing after the match.',
'Gambling harm reaches partners, children, work and mental health. Public choices include product design, advertising, access to money and support beyond a warning message.',
'AIHW’s gambling overview draws on different surveys and measures of participation and risk. Those measures are not interchangeable with industry losses, a clinical diagnosis or harm to family members. Compare the population, reference period and method before using a headline percentage.',
[('https://www.aihw.gov.au/reports/australias-welfare/gambling','AIHW: gambling evidence and definitions'),('https://aifs.gov.au/media/national-gambling-study-finds-more-australians-harmed-amid-rising-participation','AIFS: national gambling study')],
[('Reduce advertising and inducements','Can lower exposure and pressure, especially around sport. Rules need enforceable definitions and consideration of displaced advertising and sponsorship revenue.'),('Binding limits and safer product design','Loss or time limits and self-exclusion can interrupt harmful patterns. Privacy, evasion, coverage across providers and accessible account recovery matter.'),('Independent support and revenue reform','Treatment, financial counselling and family support need sustained funding. Governments and communities should examine dependence on gambling revenue rather than assume it is free money.')],
'For help, use Gambling Help Online and official self-exclusion information. For policy, ask state and federal representatives which products and advertising they regulate, what outcomes they measure and how revenue conflicts are managed. You can advocate without disclosing debts or a family member’s history.',
'Civic Ledger proposal can show gambling-derived revenue beside social costs and funded support. Mental-health and shared-wealth proposals ask what community recreation and local services could look like without depending on losses.',
[('https://www.gamblinghelponline.org.au/','Gambling Help Online'),('https://www.betstop.gov.au/','BetStop information'),('civic-ledger.html','Public revenue and accountability'),('mental-health.html','Mental health and continuity')],
'If the community wins only when someone loses, show the whole balance sheet.','target')
topic('online-safety','Online safety','A block button isn’t the whole safety plan.',
'People need protection from harassment, image-based abuse and coercion without surrendering privacy, access or a fair chance to challenge moderation.',
'eSafety’s Safety by Design approach places responsibility in how services are built and operated. Reporting routes differ by the type of online harm. A platform’s terms, a regulator’s powers and criminal law are separate layers; a removal request is not a general guarantee that every copy will disappear.',
[('https://www.esafety.gov.au/industry/safety-by-design','eSafety: Safety by Design'),('https://www.esafety.gov.au/report','eSafety: choose the right reporting route')],
[('Safer defaults and less exposure','Controls over contact, discoverability, location and sharing can prevent harm before a report. Defaults must remain understandable and usable for diverse access needs.'),('Timely moderation with appeals','Human escalation and transparent decisions can protect people and correct mistakes. Scale, languages, privacy and lawful expression complicate blanket automation.'),('Minimal-data assurance and accountability','Where age or identity checks are justified, compare proportionate methods and retention limits. Collecting more identity data can create a new breach risk.')],
'Use the service’s safety controls and the relevant eSafety route for a specific incident. Preserve only the evidence the official process asks for; do not repost harmful material. For public policy, compare response times, appeals, recurrence and user control. Children’s needs and AI-enabled financial scams have distinct rooms.',
'Sovereignty Stack proposes explicit permission and local control; the Truth Engine adds correction trails. Together they suggest systems people can inspect and contest rather than a hidden score deciding who is safe to hear.',
[('sovereignty-stack.html','Permission and control'),('truth-engine.html','Corrections and accountability'),('child-safety.html','Child safety'),('ai-scams.html','AI scams')],
'Build safety into the service, and leave people a fair appeal.','monitor')
topic('family-choices','Wanted families','We want a family. Can we afford the future?',
'Support people to have the children they want, including none. Housing, work, care, health, relationships and fears about the world deserve attention without turning parenthood into a national quota.',
'UNFPA’s 2025 survey across 14 countries identifies financial constraints, housing, job insecurity, relationships and fears about the future among barriers to desired family size. Those international results are not an Australian prevalence estimate. ABS birth and fertility statistics measure births, not the number of children people wished to have; intentions need their own evidence.',
[('https://www.unfpa.org/swp2025?lang=en','UNFPA: reproductive agency and barriers'),('https://www.abs.gov.au/statistics/people/population/births-australia/latest-release','ABS: observed births and fertility'),('https://aifs.gov.au/growing-australia/all-research/research-snapshots/young-australians-family-formation','AIFS: young Australians and family formation')],
[('Housing, childcare and secure work','Reduce recurring costs and uncertainty, with enough homes, care places and staff to make eligibility useful. Subsidies alone do not guarantee a place or affordable rent.'),('Time, healthcare and shared care','Usable leave, reproductive healthcare and flexible work can make a desired family more feasible. Coverage, career penalties and unequal caring burdens need explicit attention.'),('Wider family and household choices','Shared homes and larger care networks may spread time and risk. Consent, privacy, children’s interests and survivable exits matter; no household form suits everyone.')],
'Ask representatives to evaluate unmet intentions and wellbeing alongside birth counts. Bring a costed example of housing, care and time barriers without assuming one family speaks for everyone. Men’s fears about separation, women’s concerns about unequal care and the experiences of single and LGBTQIA+ people all deserve evidence and a fair hearing.',
'Global Group Marriages is an additional framework for self-sovereign adults sharing care, income, parenting and risk. Mutual Futures adds shared ownership, learning and time. These are substantive alternatives to explore, not a claim that a different household shape removes every cost or conflict.',
[(ggm,'Global Group Marriages'),(ggm+'household-lab.html','Private Household Lab'),('marriage-divorce.html','Marriage, divorce and U.N. of Love'),(mutual,'Mutual Futures')],
'Make a family possible. Leave the choice with the people living it.','users')
topic('marriage-divorce','Marriage & divorce','What if the family had more room?',
'Marriage, separation, money, parenting and a future together: a practical doorway into Global Group Marriages and U.N. of Love thought experiments.',
'Australia’s Marriage Act defines marriage as a union of two people, exclusive of all others. Divorce under the Family Law Act is distinct from resolving parenting or property. No-fault divorce does not promise an automatic equal property split or an automatic parenting arrangement. Australia atlas distinguishes present legal building blocks from a new multi-adult civil status.',
[('https://www.legislation.gov.au/C1961A00012/latest','Marriage Act: current text'),('https://www.legislation.gov.au/C2004A00275/latest','Family Law Act: current text'),(ggm+'countries/australia.html','Australian legal atlas')],
[('Make existing separation processes fairer','Affordable advice, timely decisions and clear financial disclosure can reduce fear and conflict. Safety screening and children’s interests must remain central; mediation is not appropriate in every case.'),('Recognise care and plan shared resources','Explore co-ownership, wills, parenting responsibilities and household agreements within current law with independent advice. Private agreements do not automatically create marriage status or override statutory rights.'),('Debate a multi-adult recognition framework','The framework proposes an additional family form that shares love, care, income and risk while preserving individual sovereignty. Reform would need clear entry, voice, property, parentage and exit rules, with safeguards against pressure.')],
'Men’s concerns about cost, time with children and process deserve a fair hearing alongside women’s experiences, financial dependence, safety and diverse families. Test claims against evidence rather than assume divorce law causes reluctance to become a parent. For personal disputes, use qualified local advice; for reform, identify the exact rule and the change sought.',
'Global Group Marriages designs the household in layers: people, love, care, resources, voice and change. Its Private Household Lab creates a local Markdown conversation sketch. U.N. of Love takes a precise comparison further: self-sovereign adult spouses across cultures, sharing romantic and sexual relationships and raising children, with a Family Assembly, Council of Care and Chamber of Repair. It is marriage-based simulacrum beside the UN, not an operating UN institution or a replacement for it.',
[(ggm+'framework.html','Read the actual group-marriage framework'),(ggm+'household-lab.html','Use the private Household Lab'),(ggm+'un-of-love.html','Enter U.N. of Love'),(ggm+'world-atlas.html','Compare six legal starting points'),('family-choices.html','Desired families and practical barriers')],
'Design the household before the household designs you.','heart')
topic('wealth-inequality','Wealth inequality','The economy grew. Whose balance sheet did?',
'Income pays this week’s bills. Wealth changes the options available next decade. A fair-go debate needs to see both, including debt and access to productive assets.',
'ABS household income and wealth statistics distinguish flows of income from net worth: assets less liabilities. The detailed 2019-20 distribution is a dated survey, not a 2026 snapshot. Aggregate household wealth can rise while some households remain exposed; averages do not reveal the distribution or who can turn an asset into spendable income.',
[('https://www.abs.gov.au/statistics/economy/finance/household-income-and-wealth-australia/latest-release','ABS: income, wealth and survey period')],
[('Tax and transfer reform','Can redistribute resources and fund common services. Design must consider avoidance, incentives, transition, asset-rich cash-poor households and who ultimately bears a tax.'),('Wider productive ownership','Employee, cooperative or community stakes can share future returns and voice. They also share risk and require finance, governance and protection against concentrated losses.'),('Universal services and lower essential costs','Housing, health, education and transport can expand real opportunity without everyone owning the same assets. Quality, access and sustainable funding determine the benefit.')],
'Ask for modelling by wealth group, age, tenure and household type, with debt and regional costs visible. Compare gains in disposable income, service access and productive ownership. A one-year average is not evidence that every generation or household is doing better.',
'Mutual Futures proposes business succession into shared ownership, technology upgrades and learning. Civic Ledger asks for transparent costs and benefits; the Braided Economy explores care and contribution alongside money. A useful pilot would show governance rights, who supplies capital and who carries losses.',
[(mutual,'Mutual Futures: shared productive wealth'),('braided-economy.html','The Braided Economy'),('civic-ledger.html','Who benefits and who pays')],
'Count the growth, then show who owns the machine.','pie-chart')
topic('migration-equations','Migration equations','People, homes, skills. Show the whole equation.',
'Migration changes demand and capacity at the same time. Housing, workforce, services, family connection and humanitarian obligations need a model with more than one moving part.',
'ABS defines net overseas migration as migrant arrivals minus migrant departures under its residence measure. It is not the same as permanent visa grants or all border crossings. National totals also do not tell a town how many homes, nurses, classrooms or transport services it needs.',
[('https://www.abs.gov.au/statistics/people/population/overseas-migration/latest-release','ABS: migration definitions and dated estimates')],
[('Coordinate intake with investment','Link population scenarios to housing, services and infrastructure delivery. Construction and training take time, and migrants can also supply the skills that expand capacity.'),('Improve skills recognition and worker protection','Make existing skills usable and prevent exploitation. Standards and local training still matter; treating migrant workers as a cheap substitute can weaken everyone’s bargaining position.'),('Adjust composition and pace transparently','Compare pathways and timing against capacity and public goals. Include family reunion, international education and humanitarian commitments, not only a headline economic total.')],
'Use a local scenario sheet: population and household formation; completed and usable homes; construction labour; service demand and staffed capacity; infrastructure lead times. Ask for ranges and feedback effects. Population divided by an assumed household size is a planning input, not a reliable standalone forecast of housing shortages.',
'Housing Simulations and Sensorium can make those assumptions visible. The separate Oceania and Native Nations projects keep places and relationships distinct, while workforce proposals ask how people already here and new arrivals can gain useful capability together.',
[('housing-simulations.html','Compare housing scenarios'),('web3-sensorium.html','Build a local evidence model'),('workforce-transition.html','Skills and work'),('international-wars.html','Separate wars and displacement room'),('security-fallacies.html','Separate security assumptions room')],
'Count the homes and the builders. Count the needs and the skills.','map')
topic('international-wars','International wars','Before the next war, show the alternatives.',
'War changes lives far beyond a battlefield. Australians can examine diplomacy, civilian protection, alliances, humanitarian support and the consequences of using force.',
'The UN Charter sets purposes and rules for international peace and security. International humanitarian law governs conduct during armed conflict, including protection of civilians; that is a different legal question from whether resort to force is lawful. Claims about a specific incident need dated, attributable evidence and competent investigation.',
[('https://www.un.org/en/about-us/un-charter','United Nations Charter'),('https://www.icrc.org/en/law-and-policy','ICRC: humanitarian law and policy')],
[('Diplomacy and conflict prevention','Negotiation, mediation and practical cooperation can reduce danger before violence escalates. Leverage, trust, enforcement and the parties’ willingness limit what a process can achieve.'),('Defence and deterrence','Capability can protect against coercion and aggression. Costs, escalation risk, civilian harm and dependence on partners must be assessed rather than assume every deployment creates security.'),('Humanitarian protection and accountability','Aid, refugee protection and lawful investigation address human consequences. Access, diversion, impartiality and safe delivery remain difficult in conflict.')],
'Ask federal representatives for the objective, legal basis, civilian-protection measures, alternatives, costs and exit conditions behind a proposed commitment. Compare independently sourced accounts and distinguish allegation, verified event and judgement. Do not turn uncertainty into invented certainty about who will win or what an intervention guarantees.',
'UNGA81 capability argument asks why advanced technology should be imagined mainly through military advantage. Civic science, health, learning and disaster resilience can also build peaceful capability. U.N. of Love offers a separate thought experiment about living with the consequences of cooperation every day.',
[(cap,'Capability without domination'),(ggm+'un-of-love.html','U.N. of Love thought experiment'),('twinkle-aukus.html','Existing AUKUS receipt'),('security-fallacies.html','Test the security assumptions'),('migration-equations.html','Separate migration room')],
'Show the purpose, the alternatives and the people who carry the cost.','flag')
topic('security-fallacies','Security fallacies','A bigger receipt is not a safety guarantee.',
'Security policy needs to say what danger it addresses, how a capability changes that danger and what happens if its assumptions fail.',
'Defence strategies and investment programmes set out official rationales and planned capabilities. They are plans to examine, not proof that a chosen purchase will deliver its intended result. Use the publication date, delivery assumptions, costs and review mechanisms when comparing a strategy with alternatives.',
[('https://www.defence.gov.au/about/strategic-planning','Defence: strategic planning and published strategies')],
[('Test military assumptions','Ask whether deterrence, readiness and delivery schedules hold under plausible scenarios. Sensitive detail may need protection, but public objectives and accountability should remain intelligible.'),('Invest in civil resilience','Energy, communications, health, food, repair and community capability can keep society functioning through disruption. They also need exercises, maintenance and evidence of benefit.'),('Diversify relationships and dependencies','Alliances, diplomacy and interoperable systems can expand options. Concentration in one supplier, network or partner can also narrow choices; diversity carries coordination costs.')],
'Use an assumption ledger: threat, evidence, proposed capability, cost, time to deliver, dependencies, failure case and an alternative. Ask what finding would trigger a change of course. Avoid the opposite fallacy too: showing a weakness in one security plan does not establish that every alternative is safe.',
'missing-middle compute network treats skills, local recovery and the ability to change providers as security assets. The Protopian Gambit proposes preparing useful shared infrastructure before a crisis. Compare that civilian capability with defence choices on their actual functions, rather than pretend a rack and a submarine do the same job.',
[(cap,'peaceful capability argument'),('web3-sensorium.html','Distributed compute and resilience'),('civic-ledger.html','An accountable assumption ledger'),('international-wars.html','Separate international wars room'),('migration-equations.html','Separate migration room')],
'What has to be true for this plan to keep us safe?','crosshair')

for n,t in enumerate(topics,31):
 body=panel('What we can check',p(t['facts'])+links(t['sources']))+panel('Choices and tradeoffs',opts(t['choices']))+panel('A practical public voice',p(t['action']))+panel('related solutions',p(t['connection'])+links(t['related']))+panel('Status and sources',p('Checked 3 October 2026. Source dates and jurisdictions remain attached to the evidence. These are choices for public discussion, not an adopted party platform.'))+links([(f'twinkle-{t["slug"]}.html',f'Twinkle {n:02d}: {t["label"]}')])
 save(t['slug'],page(t['title'],t['sub'],body))
 prev='twinkle-ancient-aliens' if n==31 else 'twinkle-'+topics[n-32]['slug']
 nxt='twinkle-tolls' if n==46 else 'twinkle-'+topics[n-30]['slug']
 seed=panel('The everyday question',p(t['sub']))+panel('The one-breath drop',p('“'+t['drop']+'”'))+panel('The serious room underneath',p(t['facts'])+links(t['sources'])+links([(t['slug']+'.html','Compare the choices and take part')]))+f'<div class="next-trail"><a class="button button-secondary" href="{prev}.html">Previous Twinkle</a><a class="button button-secondary" href="twinkle.html#seeds">All Twinkles</a><a class="button button-secondary" href="{nxt}.html">Next Twinkle</a><a class="button button-primary" href="{t["slug"]}.html">Follow-through room</a></div>'
 save('twinkle-'+t['slug'],page(t['title'],t['sub'],seed,f'Twinkle {n:02d} / {t["label"]}'))

# Upgrade existing rooms where the topic already has a door.
append('twinkle-family-violence',panel('Violence against women: safety and a future',p('Safety, housing, legal help and recovery need to connect. AIHW’s family, domestic and sexual violence evidence separates different forms of harm and reporting sources; a dated survey measure is not an annual 2026 rate. No one needs to disclose their experience to participate in public debate.')+links([('https://www.aihw.gov.au/family-domestic-and-sexual-violence','AIHW: evidence and measures'),('https://www.1800respect.org.au/','1800RESPECT: support')])+opts([('Safe housing and funded support','Emergency shelter and longer-term security make leaving safer. Capacity, accessibility and continuity must extend beyond one night.'),('Accountability and legal assistance','Orders, investigation, legal support and behaviour-change responses need timely enforcement and evaluation. A document alone does not guarantee safety.'),('Prevention and recovery','Schools, workplaces, community leadership and trauma-informed care can address patterns before and after harm. Sustained funding and outcome measures matter more than a one-off campaign.')])+p('housing, care and legal-memory rooms connect these practical layers. Ask representatives about local refuge access, time to legal support and continuity of care. Use private official support routes for personal incidents; this site does not collect identifiable allegations. In immediate danger call 000. The gender pay gap is a distinct topic.')+links([('housing-simulations.html','Housing options'),('aura-clinical-path.html','Recovery and care'),('legal-rag.html','Legal memory'),('gender-pay-gap.html','Separate pay-gap room')])))
f=D/'twinkle-family-violence.html';s=f.read_text(encoding='utf-8').replace('On average a woman a week is killed in this country by a current or former partner, and we still put the person who was hurt on the stand instead of the person who did the hurting.','Violence and coercive control can make home unsafe, and the person who was harmed should not have to carry the burden of fixing the system.');save('twinkle-family-violence',s)
append('tobacco',panel('Tobacco tax: affordability, autonomy and trust',p('People can object to an unaffordable legal habit and distrust government motives while taking health harms seriously. Compare excise objectives with actual affordability, quitting, substitution and distributional effects. Revenue is not the same as health benefit, and enforcement is not the whole conversation.')+opts([('Review the excise path','Compare a pause, redesign or reduction with continued increases. Estimate household costs, consumption, substitution and the public-budget effect, then evaluate rather than assume pass-through.'),('Make support affordable and voluntary','Accessible cessation and health care can expand choice without shaming people. Support should not depend on endorsing a tax policy.'),('Publish the trust ledger','Show revenue, health spending, enforcement costs and measured outcomes on consistent dates. Explain uncertainty in illicit-market estimates rather than dress it up as precision.')])+p('Civic Ledger offers a way to show those tradeoffs. Personal growing and reclassification remain a separate reform debate with their own current-law boundaries.')+links([('price-tax.html','Compare different tax categories'),('restricted-plants.html','Plant prohibition and personal growing reform')])) )
append('restricted-plants',panel('Compare international models without importing their law',p('Oregon’s psilocybin-services model uses licensed service centres and facilitators and sits alongside continuing US federal restrictions. It is a different framework from Australia’s authorised-psychiatrist pathway. Compare access, training, cost, adverse-event reporting and follow-up; a service framework elsewhere does not establish a right to grow or supply in Australia.')+links([('https://www.oregon.gov/oha/ph/preventionwellness/pages/psilocybin-what-are-psilocybin-services.aspx','Oregon Health Authority: how the service model works'),(tga,'Compare Australia’s medical pathway')])))
append('ancient-aliens',panel('Ancient aliens &amp; religion: compare the questions',p('A sacred account, an archaeological object and a modern extraterrestrial hypothesis can ask different things of the same image. Religious traditions also contain internal differences; one translation or television interpretation cannot speak for every believer or custodian. Explore original context, symbolism, transmission and lived meaning alongside material evidence.')+opts([('Historical and archaeological reading','Investigate date, provenance, translation and what the object’s context supports. Missing context should remain visible.'),('Religious and philosophical reading','Ask what the account means within a tradition and how its interpreters understand it. Meaning and spiritual experience are not identical to a testable claim about ancient engineering.'),('Extraordinary physical hypothesis','Identify what specific new evidence would distinguish the hypothesis from cultural symbolism, human achievement or later reinterpretation. An open question is a reason to investigate, not invented confirmation.')])+p('Truth Engine and Sensorium offer a shared evidence room; the Alien Necklace film offers creative exploration. Invite historians, archaeologists, faith communities and cultural custodians into a respectful discussion, with permission for material that is not public.')+links([('truth-engine.html','Claims, interpretations and corrections'),('alien-necklace-film.html','creative doorway')])) )
append('mental-health',panel('A separate doorway for psychedelic care',p('Evidence, supervised access, affordability and clinical safeguards deserve a focused room alongside ordinary care, housing and social support. The authorised pathway is not a guarantee of benefit or a general permission to possess or cultivate controlled substances.')+links([('psychedelic-mental-health.html','Psychedelics for mental health')])))
append('child-safety',panel('Across the wider online world',p('Age-appropriate AI is one part of online safety. Harassment, image-based abuse, privacy, moderation appeals and platform design also affect adults. Those questions have their own room.')+links([('online-safety.html','Online safety for the wider public')])))
append('twinkle-aukus',panel('Three different questions beyond the big receipt',p('International wars asks about force, diplomacy and civilian consequences. Security fallacies tests threat assumptions, dependencies and alternative investments. Migration equations examines population, homes, skills and services. Each has a distinct room.')+links([('international-wars.html','International wars'),('security-fallacies.html','Security fallacies'),('migration-equations.html','Migration equations')])))

# Titles and public labels reflect the user's wording.
for slug in ['tobacco','twinkle-tobacco']:
 f=D/f'{slug}.html';s=f.read_text(encoding='utf-8').replace('<title>Tobacco |','<title>Tobacco tax |').replace('<h1>Tobacco</h1>','<h1>Tobacco tax</h1>').replace('The price went up. The black market moved in.','The tax went up. Where’s the trust?').replace('Twinkle 28 / Tobacco','Twinkle 28 / Tobacco tax');save(slug,s)
for slug in ['fuel','twinkle-fuel']:
 f=D/f'{slug}.html';s=f.read_text(encoding='utf-8').replace('<h1>Fuel</h1>','<h1>Fuel tax</h1>').replace('<title>Fuel |','<title>Fuel tax |').replace('Twinkle 29 / Fuel','Twinkle 29 / Fuel tax');save(slug,s)
f=D/'ancient-aliens.html';s=f.read_text(encoding='utf-8').replace('<h1>Ancient aliens</h1>','<h1>Ancient aliens &amp; religion</h1>');save('ancient-aliens',s)
f=D/'twinkle-ancient-aliens.html';s=f.read_text(encoding='utf-8').replace('href="twinkle-tolls.html">Next Twinkle','href="twinkle-gender-pay-gap.html">Next Twinkle');save('twinkle-ancient-aliens',s)
append('twinkle-tolls','<div class="source-links"><a href="twinkle-security-fallacies.html">Previous Twinkle 46</a></div>')

hub=(D/'twinkle.html').read_text(encoding='utf-8').replace('Thirty Twinkles','Forty-six Twinkles').replace('twenty-six open seeds','forty-two open seeds').replace('Twenty-six more connections, waiting for your camera.','Forty-two more connections, waiting for your camera.')
hub=hub.replace('The price went up. The black market moved in.','The tax went up. Where’s the trust?').replace('Ancient aliens? Open the evidence room.','Ancient aliens &amp; religion? Open the room.').replace('No gag, said straight. A woman a week, then somewhere safe to go tonight and his behaviour on the hook.','No gag, said straight. Somewhere safe to go, sustained support and accountability for harm.')
cards=''.join(f'<a class="twinkle-card" href="twinkle-{t["slug"]}.html"><img class="seed-icon" src="../assets/topic-icons/{t["icon"]}.svg" width="36" height="36" alt="" loading="lazy"><span>{n:02d}</span><h3>{t["title"]}</h3><p>{t["sub"]}</p></a>' for n,t in enumerate(topics,31))
pos=hub.index('</div>',hub.index('href="twinkle-ancient-aliens.html"'));hub=hub[:pos]+cards+hub[pos:];save('twinkle',hub)
sm=(D/'site-map.html').read_text(encoding='utf-8').replace('</main>','<section class="section"><div class="page-copy">'+panel('More public questions',links([(f'twinkle-{t["slug"]}.html',f'Twinkle {n}: {t["label"]}') for n,t in enumerate(topics,31)]+[(t['slug']+'.html',t['label']+' policy room') for t in topics]))+'</div></section></main>');save('site-map',sm)
nav=(R/'assets/site-nav.js').read_text(encoding='utf-8').replace('Thirty Twinkles','Forty-six Twinkles')
nav=nav.replace("{ href: 'pages/twinkle.html'",''.join("{ href: 'pages/twinkle-"+t['slug']+".html', title: "+json.dumps('Twinkle '+str(n)+': '+t['label'])+", note: 'A public question with policy follow-through.' },\n        " for n,t in enumerate(topics,31))+"{ href: 'pages/twinkle.html'",1)
nav=nav.replace("{ href: 'pages/architecture.html'",''.join("{ href: 'pages/"+t['slug']+".html', title: "+json.dumps(t['label'])+", note: 'Evidence, choices and participation.' },\n        " for t in topics)+"{ href: 'pages/architecture.html'",1)
(R/'assets/site-nav.js').write_text(nav,encoding='utf-8')
ticker=json.loads((R/'content/home-ticker.json').read_text(encoding='utf-8'))
for t in topics:ticker['items'].append({'headline':t['label'],'scope':'Explore P4A','href':'pages/twinkle-'+t['slug']+'.html','note':'Distinct public topic; sourced options are not an adopted platform.'})
(R/'content/home-ticker.json').write_text(json.dumps(ticker,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
icons=json.loads((R/'content/twinkle-topic-icons.json').read_text(encoding='utf-8'));icons.update({t['slug']:t['icon'] for t in topics});(R/'content/twinkle-topic-icons.json').write_text(json.dumps(icons,indent=2)+'\n',encoding='utf-8')
inventory=[('AI data sovereignty','twinkle-breaches','sovereignty-stack'),('Violence against women','twinkle-family-violence','twinkle-family-violence'),('Gender pay gap','twinkle-gender-pay-gap','gender-pay-gap'),('Indigenous Closing the Gap','twinkle-closing-the-gap','closing-the-gap'),('Youth crime','twinkle-youth-crime','youth-crime'),('Child safety','twinkle-child-safety','child-safety'),('Psychedelics for mental health','twinkle-psychedelic-mental-health','psychedelic-mental-health'),('Super for housing','twinkle-super-housing','super-housing'),('Multinational tax avoidance','twinkle-multinational-tax','multinational-tax'),('Tobacco tax','twinkle-tobacco','tobacco'),('Restricted plants and fungi','twinkle-restricted-plants','restricted-plants'),('Fuel tax','twinkle-fuel','fuel'),('Ancient aliens & religion','twinkle-ancient-aliens','ancient-aliens'),('NDIS scams','twinkle-ndis-scams','ndis-scams'),('AI scams','twinkle-ai-scams','ai-scams'),('Aged-care scams','twinkle-aged-care-scams','aged-care-scams'),('Gambling harm','twinkle-gambling-harm','gambling-harm'),('Online safety','twinkle-online-safety','online-safety'),('Desired children, costs and fears','twinkle-family-choices','family-choices'),('Marriage and divorce','twinkle-marriage-divorce','marriage-divorce'),('Wealth inequality','twinkle-wealth-inequality','wealth-inequality'),('Migration equations','twinkle-migration-equations','migration-equations'),('International wars','twinkle-international-wars','international-wars'),('Security fallacies','twinkle-security-fallacies','security-fallacies')]
(R/'content/public-topic-inventory.json').write_text(json.dumps({'checked':'2026-10-03','requestedTopics':[{'topic':label,'twinkle':'pages/'+tw+'.html','room':'pages/'+room+'.html'} for label,tw,room in inventory],'additionalApproved':['AI copyright','Broader mental health','Sensorium upgrade'],'totalTwinkles':46},indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print('Prepared 16 additional Twinkles and policy rooms; all 24 requested topics mapped.')
