"""One-time migration: reviewed October 2026 policy rooms and Twinkle doors.
Subsequent edits belong in content/rooms; publish with build-policy-rooms.py.
"""
from pathlib import Path
import re,json,html
R=Path(__file__).resolve().parents[1];D=R/'content/rooms';D.mkdir(exist_ok=True)
def a(url,label):return f'<a href="{url}">{label}</a>'
def p(text):return '<p>'+text+'</p>'
def panel(title,text,id=''):return f'<div class="feature-panel"'+(f' id="{id}"' if id else '')+'><h2>'+title+'</h2>'+text+'</div>'
def links(*pairs):return '<div class="source-links">'+''.join(a(*x) for x in pairs)+'</div>'
def options(items):return '<div class="clue-grid">'+''.join('<div class="clue"><strong>'+title+'</strong><span>'+body+'</span></div>' for title,body in items)+'</div>'
def save(name,s):(D/(name+'.html')).write_text(s,encoding='utf-8')
template=(R/'pages/web3-sensorium.html').read_text(encoding='utf-8')
head=template[:template.index('  <main id="main">')]
foot=template[template.index('  <footer'):]
pmc='https://www.pmc.gov.au/resources/getting-it-right-building-ai-infrastructure-works-australia'
ip='https://www.ipaustralia.gov.au/tools-and-research/professional-resources/data-research-and-reports/australian-ip-report-2026/copyright/key-copyright-policy-priorities'
safe='https://www.esafety.gov.au/research/talking-to-machines-childrens-experiences-with-ai-assistants-and-companions'
mh='https://www.medicarementalhealth.gov.au/medicare-mental-health-centres'
superurl='https://www.liberal.org.au/2026/08/12/address-to-the-national-press-club'
ato='https://www.ato.gov.au/businesses-and-organisations/corporate-tax-measures-and-assurance/large-business/corporate-tax-transparency/report-of-entity-tax-information'
gas='https://www.dcceew.gov.au/energy/markets/gas-markets/gas-market-review-reforms'
beer='https://www.legislation.gov.au/C2026A00036/asmade/2025-08-01/text/original/epub/OEBPS/document_1/document_1.html'
node='https://auraofintelligence.github.io/ready-set-co-op-cultural-intelligence-node/'
def page(slug,title,subtitle,body,eyebrow='Public choices / October 2026'):
 h=re.sub(r'<title>.*?</title>',f'<title>{html.escape(title)} | P4A</title>',head)
 h=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="'+html.escape(subtitle,quote=True)+'">',h)
 return h+f'''  <main id="main"><section class="hero page-hero"><div class="hero-image"><img src="../assets/purple-festival.webp" alt="" fetchpriority="high"></div><div class="hero-content reveal"><p class="eyebrow">{eyebrow}</p><h1>{title}</h1><p class="hero-copy">{subtitle}</p><div class="hero-actions"><a class="button button-primary" href="#room">Open the room</a><a class="button button-secondary" href="twinkle.html#seeds">Twinkle seeds</a></div></div></section><section class="section" id="room"><div class="page-copy reveal">'''+body+panel('A public workbench',p('Source check: 3 October 2026. The choices here are proposals for discussion, not an adopted party platform. Follow the linked source for its jurisdiction, date and latest status.'))+f'</div></section></main>\n'+foot
consult=p('PM&amp;C’s September consultation covers large data centres and conditions for AI training, including Australian creators. Its published closing date is <time datetime="2026-10-09">9 October 2026</time>. Use the official page to check whether submissions are still accepted; after that date, follow published outcomes and later consultation rounds.')+links((pmc,'Consultation paper and submission route'))
data=[
('ai-copyright','AI copyright','My work taught the machine. Where’s my say?',
 'A song, photo, lesson or news story can carry years of work. Creators need a practical way to know how it is used; learners and small developers need rules they can actually follow.',
 panel('Three different questions',p('Training permission, rights in AI-assisted outputs and affordable enforcement are separate problems. IP Australia’s 2026 report identifies licensing, certainty about generated material and less costly enforcement as current policy priorities. A paid software subscription does not settle every right in the material fed to it.')+links((ip,'IP Australia: copyright policy priorities')))+
 panel('Choose rules that people can use',options([('Opt-in and collective licences','Creators can negotiate terms and payment, including through collective arrangements. Administration and bargaining power matter: a system affordable only to large firms can shut out smaller developers and independent creators.'),('Targeted research exceptions','A tightly defined research pathway could lower barriers to public-interest inquiry. Its scope, security, commercial reuse and effect on creator income need explicit limits; this is an option to debate, not a statement that a new exception exists.'),('Transparency and accessible remedies','Dataset provenance, rights contacts and a usable complaint process can make rights enforceable. Detailed disclosure must also handle privacy, security and legitimate confidential information. A cheap remedy still needs fair review and an appeal path.')]))+
 panel('Keep the creator in the workflow',p('Ready S.E.T. cultural node keeps viewing, storage, transcription, model work and publication as separate permission decisions. For a local film or song project, record who supplied the material, the agreed use, credits, model services, release version and correction contact. Local equipment alone does not grant copyright permission.')+links((node+'culture.html','Ready S.E.T. permission model'),(node+'projects.html','Media projects and their status'),('web3-sensorium.html','Community compute and custody')))+
 panel('Put a concrete example on the record',p('An artist, teacher, publisher or small developer can compare one actual workflow under each option: permission cost, payment, turnaround, privacy and remedy if something goes wrong. Send a redacted example to the relevant consultation or your federal representative; keep unpublished work and personal details out of a public submission.')+consult)),
('child-safety','Child safety','A chatbot shouldn’t need a babysitter.',
 'Homework help, companionship and persuasive design can arrive in the same chat window. Families deserve understandable controls and services designed around children’s wellbeing.',
 panel('What the children’s survey found',p('eSafety’s 2026 study surveyed 1,950 Australian children aged 10-17 between 2 February and 4 March. Of all surveyed children, 78% had used an AI assistant. Among children who had used an AI assistant or companion, 20% reported potentially inappropriate or harmful interactions and 32% had shared personal data or potentially sensitive information. Those last two percentages are of users, not all children.')+links((safe,'eSafety: Talking to machines')))+
 panel('Different protections, different costs',options([('Safer defaults and independent testing','Limit sensitive-data retention and test age-appropriate responses before release. Default protection reaches people who never find settings, but tests must cover real use and changing models.'),('Limits on manipulative design','Examine emotional pressure, exclusive relationships and engagement incentives. Clear boundaries can protect children while leaving room for useful, creative and accessible assistance.'),('Age assurance with minimal data','Age checks can support proportionate access rules but can also collect identity data or exclude users. Compare privacy-preserving methods, error rates, appeals and deletion before selecting one.'),('Reporting and human help','A visible report button and timely human response make failures actionable. They need funded moderation and escalation, alongside prevention rather than relying on children to police a product.')]))+
 panel('Adults can act without exposing children',p('Parents, carers, educators and youth organisations can review a service’s retention settings, complaint route and safeguards with young people. Report specific harms through the service and eSafety’s official routes. For public policy submissions, use aggregated observations and remove names, screenshots and identifying stories. This page does not collect children’s accounts.')+links(('https://www.esafety.gov.au/report','eSafety reporting routes'),('https://www.esafety.gov.au/parents','Resources for parents')))+
 panel('A local alternative needs safeguards too',p('local-first Sensorium and Ready S.E.T. learning model offer a way for libraries and community hosts to choose bounded educational tools, hold records locally and retain human supervision. Any pilot still needs child-safe staff practices, access controls, independent testing and clear limits on what it stores. A community label is not a safety certificate.')+links(('web3-sensorium.html','Local compute proposal'),(node+'cooperative.html','People and learning layer')))),
('mental-health','Mental health','Help shouldn’t be another waiting room.',
 'The cost of care is also lost time, travel, repeated explanations and a tenancy hanging by a thread. A useful mental-health system holds the person through the gaps.',
 panel('Help now has its own door',p('Medicare Mental Health Centres offer free support without a referral or appointment. They can help connect people with longer-term care and social support. They are not crisis services; check the official locator for local access. If there is immediate danger, call 000. Seeking care does not require political participation or sharing a personal story here.')+links((mh,'Find a Medicare Mental Health Centre'),('https://www.medicarementalhealth.gov.au/crisis-links','Urgent support information')))+
 panel('Beyond a single diagnosis',p('PTSD deserves its existing room, alongside depression, anxiety, severe mental illness, grief and other forms of distress. This broader room asks about affordability, continuity, culturally safe support, housing, regional access and the people doing the care. AIHW’s expenditure series helps track spending; a larger total alone does not tell a patient whether care is accessible or continuous.')+links(('twinkle-ptsd.html','The existing PTSD Twinkle'),('https://www.aihw.gov.au/mental-health/topic-areas/facilities-resources/expenditure','AIHW: mental-health expenditure')))+
 panel('Where would the next dollar go?',options([('Affordable ongoing appointments','Lower out-of-pocket costs and longer care pathways can improve continuity. Without enough clinicians, expanded eligibility can still leave a queue.'),('Teams close to home','Regional clinics, supported telehealth and stable workforce roles reduce travel. They need supervision, housing for staff and a plan for people who cannot use video care.'),('Housing and peer support','Secure housing and paid, supported peer workers can address pressures clinical appointments alone cannot remove. They complement clinical care and need clear responsibilities and sustainable funding.'),('Joined-up care with consent','A named coordinator and records shared for an agreed purpose reduce repeated explanations. More sharing also means stronger access controls and a usable correction process.')]))+
 panel('care pathways, tested in public',p('The Aura Clinical Path explores better navigation and less administration; workforce transition and intermittent retirement explore time for recovery. These are proposals, not available funded clinical services. A useful local trial would measure waiting time, out-of-pocket costs, continuity, privacy and the experience of people who stop attending, with consent and independent clinical oversight.')+links(('aura-clinical-path.html','Aura Clinical Path'),('workforce-transition.html','Work and recovery'),('housing-simulations.html','Housing choices')))+
 panel('Participation without another burden',p('Ask your local service or Primary Health Network how consumers and carers can contribute privately and be paid for their time. Ask representatives for local waiting-time and continuity measures, not only appointment totals. Bring an access problem and a proposed fix; you do not owe a campaign your health history.')+links(('https://www.health.gov.au/our-work/phn','Find the Primary Health Network pathway')))),
('super-housing','Super for housing','A deposit now. What’s left later?',
 'A home can change retirement. So can the savings used to buy it. The public choice needs both sides of that ledger, including people with little super and people still renting.',
 panel('Proposal, review and law are different',p('In the Liberal Party’s 12 August 2026 National Press Club address, super-for-housing policy was described as remaining under review. The earlier Super Home Buyer Scheme costing describes an earlier proposal, not an enacted general right to withdraw super for a deposit. Check current law and the exact scheme before treating any political announcement as an entitlement.')+links((superurl,'12 August 2026 policy status'),('https://www.pbo.gov.au/sites/default/files/2025-05/PBO-ECR-2025-2301-Super%20Home%20Buyer%20Scheme.pdf','PBO: earlier proposal costing')))+
 panel('Compare more than the deposit',options([('Withdraw retirement savings','May bring ownership forward for an eligible buyer and avoid some rent. It also removes invested capital and future compounding; additional purchasing power may affect prices where supply cannot respond.'),('Use savings as collateral','Could preserve investment exposure while helping secure finance. It links retirement security to mortgage risk and requires precise default, lender and consumer-protection rules.'),('Shared equity','A public or other partner takes a share of the home, reducing the buyer’s initial finance need. Future gains, losses, repairs, exit and buyout obligations must be clear.'),('Supply and rental security','More well-located homes and secure rental options reach people without a deposit or substantial super. Delivery takes time, construction capacity and infrastructure; tenure reform has its own landlord and tenant tradeoffs.')]))+
 panel('Show the whole household path',p('Housing Simulations room is the place to compare pathways, with the Civic Ledger recording public cost and who benefits. A useful scenario includes super balance and returns, rent avoided, deposit, interest, repayments, maintenance, transaction costs, price changes and retirement housing security. Run downside cases as well as an attractive headline. This is a public-policy comparison, not personal financial advice.')+links(('housing-simulations.html','Housing Simulations'),('civic-ledger.html','Public cost and benefit ledger')))+
 panel('Ask for distribution, not just a success story',p('Ask your federal representative for modelling by income, age, renter status, gender and existing super balance. What happens to prices and to buyers who cannot access the scheme? Ask who bears losses and whether the same budget could house more people through supply or rental measures. Compare the final rules when published rather than carrying an old election promise forward.'))),
('multinational-tax','Multinational tax','Big revenue. Show the tax trail.',
 'People want public services funded fairly and businesses competing on fair terms. That needs a tax trail that can distinguish a lawful loss from profit shifted out of reach.',
 panel('A ratio is a question, not a verdict',p('The ATO warns that its corporate transparency figures alone do not establish an entity’s effective tax rate. Company income tax applies to taxable profit, not gross revenue. Losses, offsets, group structures and timing can explain nil tax; a zero-tax entry or tax-to-revenue ratio does not establish avoidance. Ask for the relevant entity, group, period and tax base before making an accusation.')+links((ato,'ATO: how to interpret entity tax information')))+
 panel('Build on rules that already exist',p('Australia already has global and domestic minimum-tax rules. Reform choices should identify what those rules cover and where enforcement, disclosure or coordination still needs work, rather than present a minimum tax as an entirely new idea.')+links(('https://www.legislation.gov.au/F2024L01740/latest','Current multinational minimum-tax rules')))+
 panel('Different ways to close the gap',options([('Fund skilled enforcement','Audits and litigation can test risky arrangements using existing powers. They need specialist staff, time, due process and evidence; not every investigation produces extra revenue.'),('Test related-party finance and royalties','Scrutinise whether cross-border charges reflect real activities and lawful pricing. Clear rules can reduce shifting while avoiding double taxation and unpredictable treatment of ordinary trade.'),('Country-by-country and ownership transparency','More comparable accounts and visible beneficial ownership make patterns easier to examine. Scope, privacy, data quality and consistent reporting boundaries determine whether publication is useful.'),('Coordinate internationally','Shared rules and information can reduce gaps between countries. Negotiation is slower and design needs to preserve legitimate investment and treaty commitments.')]))+
 panel('A public receipt worth arguing over',p('Civic Ledger offers a useful organising proposal: identify the entity and year, link source accounts, separate revenue from profit and tax payable, record amendments and leave a correction path. For resource businesses, keep corporate tax, PRRT, royalties, subsidies and cleanup liabilities in separate columns.')+links(('civic-ledger.html','Civic Ledger'),('public-assets.html','Resources and public return')))+
 panel('Put a precise question to Parliament',p('Use the ATO source to choose a reporting year and a defined policy question. Ask representatives about enforcement capacity, published outcomes and which disclosure gaps a reform would close. If you have evidence of wrongdoing, use the ATO’s official reporting channel rather than publishing private records or labelling a company from one number.')+links(('https://www.ato.gov.au/tipoff','ATO tip-off route')))),
('tobacco','Tobacco','The price went up. The black market moved in.',
 'A serious tobacco policy has to help people quit, reduce harm and confront illicit supply without treating smokers as the enemy.',
 panel('Keep three questions separate',p('Legal tobacco prices, access to quitting support and illicit supply interact, but they are not the same measure. The Senate inquiry into Australia’s illegal tobacco market provides a public evidence trail to examine. A seizure total is not the size of the whole market, and cheap illicit products do not remove tobacco’s health harms.')+links(('https://www.aph.gov.au/Parliamentary_Business/Committees/Senate/Legal_and_Constitutional_Affairs/Tobacco2025/Report/Chapter_1_-_Introduction_-_Australias_illegal_tobacco_market','Senate tobacco inquiry'),('https://www.health.gov.au/topics/smoking-vaping-and-tobacco','Health guidance on smoking, vaping and tobacco')))+
 panel('Which mix would work?',options([('Tax with affordable cessation support','Price signals can support quitting, while practical treatment and culturally appropriate help make change more achievable. Cost pressure can fall hardest on people who remain dependent.'),('Target illicit supply and organised crime','Intelligence-led enforcement and accountable licensing can address illegal distribution. Enforcement costs money and should be judged by durable results, not only raids.'),('Review the policy mix against outcomes','Publish comparable smoking, quitting, affordability and illicit-market indicators. Adjustments need credible evaluation; a simple tax cut or increase is not a complete health or enforcement policy.')]))+
 panel('Help and participation have separate doors',p('For help to stop smoking, use Quitline on 13 7848 or talk with a health professional. For policy participation, adults can ask representatives how quitting services, enforcement funding and tax settings are evaluated together. Do not confront suspected sellers or post allegations about neighbours.')+links(('https://www.quit.org.au/','Quit support')))+
 panel('connection: make the receipt visible',p('The Civic Ledger proposal can track spending on cessation and enforcement alongside outcomes; the wider mental-health room asks whether support is affordable and continuous. Publish the programme’s purpose, costs, evidence and review date rather than a judgement about the people using it.')+links(('civic-ledger.html','Civic Ledger'),('mental-health.html','Care and continuity'),('price-tax.html','Alcohol and tax choices')))),
('fuel','Fuel','The bowser eats the pay rise.',
 'A fuel bill can be the price of getting to work, delivering food or reaching a hospital. Regional and low-income households need choices that fit the trips they actually make.',
 panel('What sits inside the price?',p('Compare wholesale fuel, exchange-rate effects, refining and distribution, retail margins and taxes. A tax change and the eventual pump-price change are not automatically identical. ACCC fuel monitoring is a better starting point than attributing every price movement to a single cause. Keep the place, fuel type and observation date attached.')+links(('https://www.accc.gov.au/consumers/petrol-and-fuel','ACCC petrol and fuel information')))+
 panel('Relief now and less exposure later',options([('Temporary tax relief','Can give broad and fast relief if passed through. It has a public-budget cost, also benefits high consumption and needs a visible end date and price monitoring.'),('Targeted transport assistance','Can direct help to people facing unavoidable travel and limited income. Eligibility and administration must not make it harder to receive than it is worth.'),('Competition and price transparency','Comparable local prices and scrutiny of supply can improve shopping and accountability. They cannot manufacture a competing station or bus route in every remote community.'),('Transport and electrification investment','Public transport, freight efficiency and suitable electric vehicles can reduce oil exposure. Upfront cost, charging, grid access and regional service design determine who can benefit.')]))+
 panel('Make a local trip ledger',p('public-assets and food-security rooms connect household travel to freight, shared services and infrastructure. Use a local Sensorium brief to compare real routes: cost, time, accessibility, charging or fuel access, and disruption. A model should include people who cannot drive and workers outside commuter hours.')+links(('public-assets.html','Infrastructure choices'),('food-security.html','Food and freight'),('web3-sensorium.html','Local models')))+
 panel('Bring the journey to the decision',p('Ask your council, state transport agency and federal representative which lever each controls. Compare a recurring trip under the options above and request a costed alternative, with operating funding as well as construction. Use official fuel-price information for your state; keep home addresses and daily routines out of public examples.'))),
('ancient-aliens','Ancient aliens','Ancient aliens? Open the evidence room.',
 'Extraordinary objects, old sky stories and astonishing engineering deserve a proper look. Bring curiosity, the source trail and more than one possible explanation.',
 panel('One object. Several possible stories.',p('Choose a specific object, site, text or image. Start with its collection record, excavation context, dating method, provenance and the interpretations offered by people who study or care for it. A dramatic photograph can raise a question without resolving who made something or how. The British Museum’s collection search and Australian museum collections offer starting records; check the individual object and its history.')+links(('https://www.britishmuseum.org/collection','Search object records'),('https://www.nma.gov.au/explore/collection','National Museum of Australia collection')))+
 panel('How would you investigate?',options([('Reconstruct human techniques','Compare tools, materials, labour, trade and experimental archaeology. A reconstruction can test feasibility without proving that the exact ancient sequence is known.'),('Explore cultural accounts in context','Read original language, translation history and living interpretation with custodians. A story can carry cultural and historical meaning without being reducible to a literal technology diagram.'),('Test an extraordinary hypothesis','State what observation would distinguish it from known engineering, later alteration or a mistaken date. Identify missing evidence and a feasible test; uncertainty leaves a question open rather than confirming a visitor.'),('Open records and reproducible models','Improve public access to collection records and labelled reconstructions. Access must respect sensitive sites, cultural authority, provenance and limits on reuse.')]))+
 panel('The policy underneath the mystery',p('The public choices include museum and archive funding, research access, cultural heritage protection and transparent handling of unusual reports. More open records can support independent checking; sensitive locations and cultural material may need restricted access. Funding speculative tests also has an opportunity cost, so define a modest question and publish the result even if it changes the story.')+links(('https://www.naa.gov.au/explore-collection','Explore Australian archival records'),('truth-engine.html','P4A Truth Engine')))+
 panel('tools for a good rabbit hole',p('The Truth Engine proposes claim labels, competing explanations and corrections. The Sensorium adds source-labelled spatial reconstructions and simulations; a compelling render remains a model. Alien Necklace film is a creative doorway, with its own story and status. UAP observations have a separate Twinkle, and Deep time addresses climate change, with flooding as one example.')+links(('alien-necklace-film.html','Alien Necklace film'),('web3-sensorium.html','Sensorium models'),('twinkle-uap.html','UAP: no giggle tax'),('twinkle-deep-time.html','Deep time and climate change')))+
 panel('Bring one traceable question',p('Use a museum’s enquiry route or a public archive record to seek a source. Write down the object identifier, date, competing explanations and what evidence would change your view. Join lawful, permission-based public archaeology or citizen-science activities; leave protected sites and objects in place. Share a source-linked argument, not someone else’s sacred or private material.')))
]
for n,(slug,label,title,sub,body) in enumerate(data,23):
 save(slug,page(slug,label,sub,body+links(('twinkle-'+slug+'.html',f'Twinkle {n:02d}: {label}'))))
 prev='twinkle-ptsd' if n==23 else 'twinkle-'+data[n-24][0]
 nxt='twinkle-tolls' if n==30 else 'twinkle-'+data[n-22][0]
 seed=panel('The everyday gripe',p(sub))+panel('Take it to the serious room',p('Start with a recognisable moment: '+title+' Let the everyday question lead into evidence, competing choices and something people can do.')+links((slug+'.html',label+': evidence, options and participation')))+panel('Make it yours',p('Use your own place, voice and verified example. Keep the joke aimed at the machinery. Existing claims and new footage need their source and permission trail; no finished clip is claimed for this seed.'))+f'<div class="next-trail"><a class="button button-secondary" href="{prev}.html">Previous Twinkle</a><a class="button button-secondary" href="twinkle.html#seeds">All seeds</a><a class="button button-secondary" href="{nxt}.html">Next Twinkle</a><a class="button button-primary" href="{slug}.html">Follow-through room</a></div>'
 save('twinkle-'+slug,page('twinkle-'+slug,title,sub,seed,f'Twinkle {n:02d} / {label}'))

alcohol=panel('The draught freeze is law',p('The Excise Tariff Amendment (Draught Beer) Act 2026 received assent on 8 April 2026. It sets the indexation factor to one for specified draught-beer rates on 1 August 2025, 1 February 2026, 1 August 2026 and 1 February 2027. The old “every February and August” line is therefore stale for those rates. It does not describe every packaged beer, spirit or wine tax.')+links((beer,'Read the enacted draught-beer amendment')))+panel('The price of a drink has several levers',options([('Targeted hospitality relief','A draught-specific concession can support on-premise trade. Its fiscal cost and actual benefit to venues, staff and customers need measurement.'),('Review consistency across alcohol taxes','Compare beverage categories, alcohol content and administrative complexity. Reform creates winners and losers; transition and health effects need to be explicit.'),('Fund harm reduction and treatment','Services, prevention and late-night transport address costs not shown on a menu. They need reliable funding and evidence, rather than assuming price policy does every job.')]))+panel('Show the pub receipt',p('Ask what changed in tax, wholesale costs, rent, wages and the menu price over the same period. Civic Ledger proposal can make the public cost and review date visible without pretending a venue’s entire bill is tax. Ask representatives how any concession’s pass-through and health effects will be evaluated.')+links(('civic-ledger.html','Civic Ledger'),('twinkle-beer-tax.html','Beer-tax Twinkle'),('tobacco.html','Tobacco choices'),('fuel.html','Fuel choices')))
save('price-tax',page('price-tax','The price and the tax','A schooner, a packet and a tank of fuel have different rules and different public consequences.',alcohol))

def deepen(slug,body):
 s=(D/(slug+'.html')).read_text(encoding='utf-8') if (D/(slug+'.html')).exists() else (R/'pages'/(slug+'.html')).read_text(encoding='utf-8')
 # Keep original media and seed material; add reviewed follow-through before the existing trail.
 if '<div class="next-trail">' in s:s=s.replace('<div class="next-trail">',body+'<div class="next-trail">',1)
 else:s=s.replace('</main>','<section class="section"><div class="page-copy">'+body+'</div></section></main>',1)
 save(slug,s)
work=panel('Job apocalypse: what can workers actually choose?',p('Jobs and Skills Australia measures exposure at task level. Exposure is not a predicted percentage of jobs lost: adoption, demand and workplace decisions shape the outcome.')+links(('https://www.jobsandskills.gov.au/studies/generative-artificial-intelligence-capacity-study/our-gen-ai-transition-exposure','JSA: exposure'),('https://www.jobsandskills.gov.au/studies/generative-artificial-intelligence-capacity-study/our-gen-ai-transition-adoption','JSA: adoption'))+options([('Paid training and transition income','Give people time to learn without losing the rent. Courses need links to real work, accessible entry and outcome checks; a credential alone does not create a job.'),('Worker consultation and productivity sharing','Workers can help choose tasks and negotiate shorter hours, wages or better services. Gains vary by workplace; bargaining power and transparent measurement matter.'),('Entry-level pathways and public procurement','Apprenticeships, supervised junior roles and training requirements in public contracts can preserve learning routes. They cost time and money and should reward genuine skill transfer, not attendance figures.')])+p('Try Everything Once, intermittent retirement and Ready S.E.T. cooperative are proposals for broader experience, recovery and paid local capability. They are not a funded entitlement. Ask your employer or union to map changing tasks, paid learning time, consultation and who receives productivity gains before a rollout.')+links(('https://auraofintelligence.github.io/mutual-futures/','Mutual Futures workbench'),(node+'cooperative.html','Ready S.E.T. cooperative roles')))
deepen('workforce-transition',work)
sovereign=panel('Australian hosting is only one question',p('Ask who operates the service, which jurisdictions apply, who controls encryption keys, what purpose is allowed, how long data and backups remain, which subcontractors can access them, and how deletion, export and exit work. OAIC’s APP 8 guidance describes cross-border obligations and exceptions; geography alone does not answer them.')+links(('https://www.oaic.gov.au/privacy/australian-privacy-principles/australian-privacy-principles-guidelines/chapter-8-app-8-cross-border-disclosure-of-personal-information','OAIC: APP 8'),('https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/guidance-on-privacy-and-developing-and-training-generative-ai-models','OAIC: AI training privacy'))+options([('Keep sensitive work on-device','Reduce external disclosure, with limits on capacity and a need for safe backups and recovery.'),('Use a community or institutional node','Share serious capability and local skills, while funding administration, access control and independent oversight.'),('Choose an accountable external service','Gain scale and specialist operations, with enforceable purpose limits, subcontractor visibility and a tested exit plan.')])+p('First Nations collective authority must be addressed alongside individual privacy. NIAA’s Framework for Governance of Indigenous Data and Ready S.E.T.’s separate permission operations offer practical questions for a local agreement. Ask a school, council or health provider to publish a plain-language custody and exit sheet; do not put private records in a public submission.')+links(('https://www.niaa.gov.au/resource-centre/framework-governance-indigenous-data','Indigenous data governance framework'),(node+'culture.html','Ready S.E.T. cultural permissions'),('web3-sensorium.html','Compute choices')))
deepen('sovereignty-stack',sovereign)
resources=panel('Resources: public return and affordable supply',p('DCCEEW’s September 2026 update reports that around three-quarters of Australian gas production is exported. The announced reservation scheme is intended to commence on 1 July 2027, with supply obligations expected from 1 January 2028. The proposed obligation is equivalent to 20% of annual LNG export volumes, adjustable downwards for domestic security needs. Exposure-draft consultation closed on 24 September 2026; current rules remain until new arrangements are implemented.')+links((gas,'Gas reform design, dates and status'))+options([('Reservation and supply obligations','Can secure gas for local contracting, but design affects investment, trade commitments and who qualifies. Reserved volume alone is not a household retail-price guarantee.'),('Efficiency and electrification','Reduce exposure to gas costs where suitable alternatives exist. Upfront investment, renters’ control and industrial process limits must be addressed.'),('Royalties, tax and public stakes','Change the public return from extraction or ownership. Revenue design, risk, investment incentives and cleanup responsibilities differ from the affordability question.')])+p('public-resource receipt should record production, exports, royalties, PRRT, corporate tax, subsidies, cleanup liabilities and local benefits with the same period and clear entity boundaries. Zero corporate tax is not proof of avoidance. Resource ownership also does not establish Crown surface tenure: land rights, mineral rights, Native Title and approvals need their own records.')+p('Ask your representatives for a project-level receipt and the assumptions behind any claimed bill reduction. Use published gas consultation outcomes and later instruments to follow implementation; the September submission window is closed.')+links(('multinational-tax.html','Read corporate tax figures fairly'),('civic-ledger.html','Build the public receipt')))
deepen('public-assets',resources)
deepen('housing-simulations',panel('Put super access beside the alternatives',p('Model withdrawals, collateral, shared equity, new supply and secure renting on comparable assumptions. Include rent avoided, mortgage interest, compounding forgone and price effects. The Coalition described super-for-housing policy as under review on 12 August 2026; an earlier costing is not law. Ask who benefits when a household has little super or cannot service a mortgage.')+links(('super-housing.html','Detailed super-for-housing choices'),(superurl,'Dated policy status'))))
deepen('aura-clinical-path',panel('PTSD care and the wider care system',p('Trauma-informed care needs continuity, consent, choice and an affordable path to qualified help. Administrative relief is useful only if people can still reach a human, correct records and refuse automated handling. A digital navigation proposal does not establish clinical effectiveness.')+options([('A named care coordinator','May reduce repeated histories and missed handovers, but needs time, training and consent.'),('Peer and community support','Can reduce isolation and improve navigation with paid supervision; it complements clinical treatment.'),('Accessible specialist pathways','Need funding, workforce and regional access, not simply a new referral form.')])+p('Aura direction should be evaluated on waiting time, continuity, patient choice and safe escalation. Ask services for private consumer-feedback routes. Public advocacy can describe a system failure without exposing a person’s trauma history.')+links(('mental-health.html','Wider mental health and help now'),(mh,'Official care access'))))
deepen('truth-engine',panel('UAP: no giggle tax, a better observation record',p('NASA’s UAP study asks what data exist, what new observations would help and how reporting can improve. That is a useful public method: preserve time, place, original media, instrument limits and competing explanations. An unresolved observation remains unresolved; neither ridicule nor an invented confirmation adds evidence.')+links(('https://science.nasa.gov/uap/','NASA UAP study and report'),('https://www.naa.gov.au/explore-collection','Search Australian archival records'))+options([('Open archival access','Makes historical reports inspectable, with privacy and security redactions explained.'),('Better civilian reporting','Consistent observation fields improve comparison, but need moderation and protection of witnesses’ identities.'),('Targeted instrumentation','Calibrated observations can test particular questions; equipment and analysis cost money and require a defined research purpose.')])+p('Truth Engine and Sensorium can hold the claim, its source, corrections and competing models. Search a named archive record, ask for its release status or document a lawful observation without trespassing or exposing private locations. Ancient-history questions have their own room.')+links(('twinkle-uap.html','Existing UAP seed'),('ancient-aliens.html','Ancient aliens evidence room'))))
deepen('community-insurance',panel('Deep time: climate change and the planning horizon',p('A one-in-100 annual chance does not promise a century between floods. Repeated events can occur, and changed climate, drainage, land use or catchment conditions can change the risk. Read the model’s date, scenarios and limits before treating a historical label as a guarantee.')+links(('https://www.bom.gov.au/water/floods/','Bureau of Meteorology: flood information'))+options([('Protect and adapt','Drainage, raised services and building work can lower damage; residual risk and downstream effects remain.'),('Change where and how we build','Planning limits and voluntary relocation can reduce exposure but affect home, livelihood, community and public budgets.'),('Insurance and mutual support','Can spread financial shocks while exclusions, affordability, reinsurance and lawful operation need careful design. It does not physically prevent a flood.')])+p('Sensorium and local twin builders can compare scenarios with source dates and uncertainty visible. Ask council for the latest flood study and evacuation information, then test alternatives in a public model without publishing household vulnerability. Deep time is the climate-change topic; flooding is one example. Ancient aliens remains a separate topic.')+links(('twinkle-deep-time.html','Existing Deep time seed'),('web3-sensorium.html','Source-labelled local scenarios'))))
deepen('web3-sensorium',panel('Large data centres: inspect the actual bargain',p('Water demand depends on the cooling design, climate, operating load and water source; grid effects depend on connection and supply arrangements. Ask for project-specific estimates, measured operation and who pays for new infrastructure. A blanket claim that every data centre drinks more than its town cannot substitute for the numbers.')+options([('Conditions on large projects','Require transparent costs, resource plans and community benefits, while keeping approvals and compliance clear.'),('Shared local capability','missing-middle proposal adds public access, training and portable workloads. It needs a host, operators and a realistic budget.'),('Demand and siting choices','Compare efficient workloads, suitable cooling and locations against local constraints. Moving impacts elsewhere is not the same as reducing them.')])+consult))

# Existing Twinkles keep their media; each gains a dated substantive doorway.
for slug,room,label in [('workforce','workforce-transition','Job apocalypse'),('datacentres','web3-sensorium','Data-centre choices'),('breaches','sovereignty-stack','Custody, deletion and exit'),('resources','public-assets','Resources and public return'),('beer-tax','price-tax','The draught freeze and tax choices'),('housing','housing-simulations','Housing choices'),('ptsd','aura-clinical-path','PTSD and continuity of care'),('uap','truth-engine','No giggle tax'),('deep-time','community-insurance','Climate change and public risk models')]:
 deepen('twinkle-'+slug,panel('Follow the policy through',p('Updated 3 October 2026. '+label+' has a deeper room with evidence, distinct options and practical participation. The choices remain open for discussion.')+links((room+'.html',label))))

# Correct inherited claims without removing the seeds or video material.
replacements={
 'Beer tax gets a payrise. You don\'t.':'Beer tax froze. Did your schooner?',
 'Up every February and August, automatically. Then taxes and donations on the same public rail.':'Draught indexation is frozen through February 2027. Follow the actual tax and the menu price.',
 'The data centre drinks more than the town.':'Big data centre. Where’s the local deal?',
 'Resources leave for a pittance, the profits buy the megaphones, then every deal public with an expiry date.':'Resources leave by the shipload. Follow the public return, the contracts and the influence trail.',
 'AI job shock? Train wider.':'Job apocalypse? Give us a real plan.',
}
for slug in ['twinkle-beer-tax','twinkle-datacentres','twinkle-resources','twinkle-workforce']:
 s=(D/(slug+'.html')).read_text(encoding='utf-8')
 for old,new in replacements.items():s=s.replace(old,new)
 if slug=='twinkle-beer-tax':
  s=s.replace('the beer tax goes up every February and every August, automatically, no debate, no delay, among the highest beer taxes going.','the draught-beer indexation freeze is now law, but a menu price still has rent, wages, wholesale costs and margins inside it.')
  s=s.replace('Everyone who buys a beer watches indexation happen twice a year with total reliability.','The draught freeze changes the tax story; compare the actual category and date.')
  s=s.replace('"If the beer tax can raise itself twice a year automatically, donations can disclose themselves the same day. Same computer."','"You can publish a tax change. You can publish who paid for the campaign. Let’s see both receipts."')
  s=s.replace('updating as reliably as the beer tax does','with dates, categories and corrections visible')
 if slug=='twinkle-datacentres':
  s=s.replace('with a water allocation the local growers would kill for and a grid connection your power bill quietly helps fund, and the deal that made it all happen is commercial-in-confidence. Compute is the new mine, except the royalty cheque never arrives.','and residents want the water source, cooling demand, grid costs and public benefits explained. The answers depend on the actual project and its agreements.')
  s=s.replace('Nobody local ever sees the terms.','Residents should be able to inspect the public terms and challenge the assumptions.')
 if slug=='twinkle-resources':
  s=s.replace('shipped out for a pittance while the profits buy megaphones and influence','and their public return, contracts and influence trails').replace('resources leaving by the shipload for a pittance','resources leaving by the shipload with the public return hard to follow')
  start=s.index('Straight to camera:');end=s.index('</p>',start)
  s=s[:start]+"Straight to camera: iron, gas, coal and sand leave by the shipload. Show us the public receipt: production, exports, royalties, taxes, subsidies, cleanup and local benefit. Keep corporate profit and political influence traceable without assuming one tax number tells the whole story. The trapdoor is daylight with a clock on it: publish the terms and review dates. This seed is open: film your own shipload rant."+s[end:]
 save(slug,s)

# Extend the existing sequence into the new eight seeds.
s=(D/'twinkle-ptsd.html').read_text(encoding='utf-8')
s=re.sub(r'<a class="button button-secondary" href="twinkle-tolls.html">[^<]*</a>','<a class="button button-secondary" href="twinkle-ai-copyright.html">Next Twinkle 23</a>',s)
if 'Next Twinkle 23' not in s:s=s.replace('<div class="next-trail">','<div class="next-trail"><a class="button button-secondary" href="twinkle-ai-copyright.html">Next Twinkle 23</a>',1)
save('twinkle-ptsd',s)

# Hub and sitemap preserve all existing content.
hub=(R/'pages/twinkle.html').read_text(encoding='utf-8')
for old,new in replacements.items():hub=hub.replace(old,new)
hub=hub.replace('Twenty-two clips, four worked examples and eighteen open seeds','Thirty Twinkles, four worked examples and twenty-six open seeds').replace('Eighteen more connections, waiting for your camera.','Twenty-six more connections, waiting for your camera.')
cards=''.join(f'<a class="twinkle-card" href="twinkle-{slug}.html"><span>{n:02d}</span><h3>{title}</h3><p>{sub}</p></a>' for n,(slug,label,title,sub,body) in enumerate(data,23))
pos=hub.index('</div>',hub.index('href="twinkle-ptsd.html"'));hub=hub[:pos]+cards+hub[pos:]
icons=dict(zip(['tolls','food','insurance','workforce','housing','power','health','family-violence','childcare','beer-tax','datacentres','breaches','resources','triple-zero','aukus','revolving-door','donations','olympics','treaty','uap','deep-time','ptsd','ai-copyright','child-safety','mental-health','super-housing','multinational-tax','tobacco','fuel','ancient-aliens'],['truck','shopping-cart','umbrella','briefcase','home','zap','heart','shield','smile','coffee','server','lock','layers','phone-call','anchor','repeat','dollar-sign','award','file-text','radio','cloud-rain','activity','edit-3','eye','message-circle','key','globe','slash','droplet','compass']))
for slug,icon in icons.items():hub=hub.replace(f'<a class="twinkle-card" href="twinkle-{slug}.html">',f'<a class="twinkle-card" href="twinkle-{slug}.html"><img class="seed-icon" src="../assets/topic-icons/{icon}.svg" width="36" height="36" alt="" loading="lazy">')
hub=hub.replace('</head>','  <link rel="stylesheet" href="../assets/twinkle-topics.css">\n</head>')
save('twinkle',hub)
sm=(R/'pages/site-map.html').read_text(encoding='utf-8')
sm=sm.replace('</main>','<section class="section"><div class="page-copy">'+panel('New Twinkle doors and policy rooms',links(*[(f'twinkle-{x[0]}.html',f'Twinkle {n:02d}: {x[1]}') for n,x in enumerate(data,23)],*[(x[0]+'.html',x[1]+' policy room') for x in data],('price-tax.html','Alcohol: price and tax')))+ '</div></section></main>')
save('site-map',sm)
nav=(R/'assets/site-nav.js').read_text(encoding='utf-8').replace('Twenty-two seeds','Thirty Twinkles')
nav=nav.replace("{ href: 'pages/twinkle.html'",''.join("{ href: 'pages/twinkle-"+x[0]+".html', title: 'Twinkle "+str(n)+": "+x[1]+"', note: 'Evidence, options and a deeper policy room.' },\n        " for n,x in enumerate(data,23))+"{ href: 'pages/twinkle.html'",1)
nav=nav.replace("{ href: 'pages/architecture.html'",''.join("{ href: 'pages/"+x[0]+".html', title: '"+x[1]+"', note: 'Public choices and participation.' },\n        " for x in data)+"{ href: 'pages/price-tax.html', title: 'Price and tax', note: 'Alcohol categories and the enacted draught freeze.' },\n        { href: 'pages/architecture.html'",1)
nav=nav.replace('The thirsty grey shed','The local infrastructure bargain')
(R/'assets/site-nav.js').write_text(nav,encoding='utf-8')
ticker=json.loads((R/'content/home-ticker.json').read_text(encoding='utf-8'))
for slug,label,*_ in data:
 match=next((x for x in ticker['items'][23:] if x['headline'].lower()==label.lower()),None)
 if match:match['href']='pages/twinkle-'+slug+'.html'
 else:ticker['items'].append({'headline':label,'scope':'Explore P4A','href':'pages/twinkle-'+slug+'.html','note':'Source-backed policy options; not an adopted platform.'})
if not any(x['headline']=='Job apocalypse' for x in ticker['items']):ticker['items'].append({'headline':'Job apocalypse','scope':'Explore P4A','href':'pages/twinkle-workforce.html','note':'Task exposure is not predicted job loss.'})
ticker['checked']='2026-10-03'
(R/'content/home-ticker.json').write_text(json.dumps(ticker,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(R/'content/twinkle-topic-icons.json').write_text(json.dumps(icons,indent=2)+'\n',encoding='utf-8')
print('Prepared eight new Twinkles, nine policy rooms, existing-room depth and hub/navigation sources.')
