"""Apply a gripe-specific relevance review; retain the complete prior map in history."""
from pathlib import Path
import copy,json
R=Path(__file__).resolve().parents[1];OUT=R/'docs/planning'
SPECIFIC_REMOVAL_REASONS={
 (21,'micronova'):'Actual page read: combines past abrupt-climate records with geomagnetic/solar hypotheses and a catastrophe-monitoring build. It is not evidence establishing the climate-change gripe or a substitute for the missing climate-policy case.',
 (21,'solar-swarm'):'Actual page read: teaching-grade Solar System mission-design models, explicitly not launched hardware. It does not supply a climate-policy or local climate-adaptation model.',
 (20,'solar-swarm'):'Actual page read: mission design and sensor allocation do not supply a UAP observation, disclosure record or chain of custody.',
 (40,'visa'):'Actual page read: explicitly for Australian passport holders travelling abroad. Entry/activity permissions abroad do not model inward Australian migration or local service capacity.',
 (46,'medicinal-venture'):'Actual page read: traceable culinary products, sourcing permissions and a separate medicinal-research pathway. It contains no adult personal-cultivation or prohibited-plant reform mechanism.',
 (24,'trust-index'):'Index and actual Australia guide read: general lab comparisons plus family/school privacy advice, not child-companion design controls, guardian rights or tested escalation. Removed as a solution association, not because beginner advice has no value.',
 (24,'matrix'):'Actual README read: personal records/interface and local experimental word-pattern tools; some screens are placeholders. No child-companion safeguards or guardian/child rights workflow is demonstrated.',
 (35,'trust-index'):'Actual index/guide read: general lab comparison and scam-awareness warnings, not voice authentication, bank recovery or an implemented impersonation-verification workflow.',
 (22,'clinical'):'Original clinical document read: explicitly a dementia proof-of-concept with narrative/clinical profiling. It does not establish a PTSD claims or veteran/first-responder care mechanism.',
 (34,'clinical'):'Original clinical document read: dementia profiling and research validation, not verification that billed NDIS support was delivered.',
 (34,'aged-plan'):'Original document read: care/autonomy monitoring and a commercialisation/regulatory plan; its autonomy audit trail is not a delivered-service/invoice matching mechanism.',
 (36,'aged-plan'):'Original document read: daily-choice/autonomy records and proposed monitoring do not verify billed visits or implement scam recovery.',
 (39,'healthy-coops'):'Actual page read: shared wellbeing, owner-held reflection and illustrative chamber hardware-sharing costs. No tobacco-excise mechanism or tobacco-specific cessation programme is supplied.',
 (45,'healthy-coops'):'Actual page read: chamber/wellbeing access costs do not constitute a financing model for psychedelic preparation, administration and clinical follow-up.',
 (43,'micronova'):'Actual page read: catastrophe, geomagnetic and solar research is not an ancient-alien object, chronology or competing-construction evidence dossier.'
}
# Number | retained local references | retained cross-repo references | directly applicable material | gap | next work
DECISIONS='''1|S2|local-gov,wealth|The public-contract proposal and local-government submission address asset terms and public returns; the wealth-fund page supplies an asset-return mechanism.|No worked toll concession or operating toll-contract observatory is verified. General legal-method pages do not fill that gap.|Work through one motorway concession, extensions, escalation formula, ownership and lawful review points.
2|R1|shared-table,ai-kitchen-pdf,food-expansion,ai-kitchen-original|Shared Table and the food-specific sources directly address shared purchasing, growing, storage and avoidable food waste.|The food documents establish ideas, not measured household savings. General contribution schemes and transport projects are not needed to establish this connection.|Develop one household/street food-basket case with waste, purchasing, storage and delivery costs.
3|R2|mutual-care|Mutual Care directly connects prevention, transparent reserves and shared risk, including its specific proposal for C-Hour prevention receipts. Those receipts recognise prevention; they are not an insurance product.|No operating mutual product or actuarial portfolio is established; a generic ledger or C-Hour receipt is not insurance.|Compare explicit mutual structures, exclusions, reserve adequacy and catastrophe exposure for one peril.
4|R3,R4|mutual-futures,node,capital,succession|Mutual Futures supplies succession and capital-comparison mechanisms; Ready S.E.T. explicitly includes employment, training and local technical roles.|No operating placement programme or acquisition fund is established. Generic contribution recognition is not paid workforce transition.|Develop a sector-switch and owner-retirement case covering paid learning, wages, ownership, finance and risk.
5||housing,housing-docs,capsules,living-twin|Supported living, the working document library and Capsule Surge Lab directly address housing transitions and temporary capacity. Living Twin models housing, residents, jobs and service dependencies as a work-in-progress simulation. Multi-site is the actual local collaboration Luke was invited into with Indigenous people on Straddie.|These local examples do not establish a national housing-policy framework or the separately intended housing-policy source. Twin model outputs are not validated forecasts, and its README explicitly disclaims Traditional Owner review or authority.|Retain the existing many-pathway P4A room; use these bounded local examples only where they illuminate tenure, supported living, adaptation or temporary versus lasting housing.
6||energy,wealth|Clean Energy Superpower directly addresses generation, storage and sharing; community wealth funds offer a concrete ownership/returns mechanism.|No operating bill reduction is established. A local-compute hardware project does not answer household electricity pricing.|Compare an actual tariff, capital/maintenance budget and community ownership case.
7|||The landing room includes primary Medicare information, but its dementia and experimental-health proposals do not directly answer the GP-cost gripe.|No directly applicable developed project addressing bulk-billing affordability or GP access was verified.|Develop the primary-care access, patient-cost and workforce case first; do not use unrelated health projects to fill it.
8||women-children,housing|The women-and-children and supported-housing pages directly address safe places and the transition to longer-term accommodation, within the actual local collaboration.|No refuge, commissioned pathway, mandate or wider endorsement is established. Generic legal worksheets do not provide a safety service.|Develop a specialist-led safe-exit and housing-capacity case, keeping sensitive locations private.
9|R7|ggm|Global Group Marriages explicitly explores pooling adult time, resources and child/elder care. It is a directly relevant optional household thought experiment, rather than a licensed childcare service.|Shared household care does not establish lower licensed-childcare fees, available places or educator supply. The formal-service affordability gap remains.|Build the childcare fee/subsidy, place-capacity and staffing-cost comparison with childcare-specific evidence.
10||legal-engine|Australian Legal Engine is a concrete supporting tool for retrieving the dated excise provisions; the substantive beer-price material is already in P4A's Price and Tax room.|No separate developed beer-tax solution was found. Retrieval code is not a tax policy or pass-through model.|Build a schooner price decomposition with actual duty dates and venue costs; label retrieval as supporting work only.
11|R4,R5,R6,R14,R18,S1|node,senate,eggs,hardware|UNGA81 and Ready S.E.T. directly develop the missing-middle argument. The submissions, hardware proposal, candidate node and linked scene/brief tools supply specific infrastructure, workload and planning material.|The rack and network are proposals; working brief/scene tools do not demonstrate installed compute or environmental outcomes.|Compare useful workloads, custody, skills, cost, power/cooling and recovery in one node brief, preserving the explicit UNGA81/Ready S.E.T. connection.
12||data-sovereignty,matrix,fair-go-ai|Data-sovereignty permissions, owner-held storage/export and A Fair Go for the AI Age provide specific custody, access and revocation mechanisms that could reduce unnecessary copying of personal data.|These are limited data-minimisation mechanisms, not an audited identity wallet, breach-remediation service or proof that local hardware is secure.|Use one licence-verification workflow to test what is collected, retained, disclosed, revoked and recovered.
13|R2|country-deals,indigenous-deals,sand|Country-deal and Indigenous wealth proposals address resource equity, control and returns. The Sand document specifically proposes directing mineral royalties, asset dividends and lease income into a community wealth fund.|These are proposed return mechanisms, not an agreed deal, proven engineering economics or authority for a Nation. Speculative sand, energy and reclamation scenarios remain clearly identified as proposals.|Build one resource-deal receipt covering terms, equity, royalties, liabilities and community return with the actual parties and authority identified.
14||kiosks,mesh-pdf,kiosk-pdf|Disaster Kiosks and the mesh documents address information and communications continuity during outages; that is the direct emergency-access connection.|This is a continuity connection, not a Triple Zero replacement or an operating emergency-call solution. The kiosk PDFs were file/title verified only.|Map one outage dependency chain and identify the emergency-authority interfaces a tested continuity plan would need.
15|S1|aukus,space-gambit|The AUKUS submission and Space Gambit directly examine defence spending and alternatives; the Senate document contains an explicit opportunity-cost comparison.|Planning node allowances are not quotes, and civilian nodes do not perform submarine functions. Generic hardware projects are unnecessary extra associations.|Compare the authored scenarios with defence costs, delivery and dependencies; keep the ISS gambit identified as a thought experiment.
16||legal-engine|Legal retrieval code can support checking the exact cooling-off and conflict rules in a worked public-official employment chain.|No developed revolving-door register was verified. A general legal-reading method is not an institutional accountability system.|Build one sourced portfolio-to-employer timeline with the applicable rule, response and correction route; use retrieval only as a supporting tool.
17||legal-engine|Australian Legal Engine can support retrieval of the exact donation-disclosure rules in a dated case. The inspected UNGA81 transcript discusses truthfulness but does not contain the previously attributed near-transfer-speed donation proposal.|No developed donation-disclosure system is established. Generic truthfulness arguments, C-Hour and legal worksheets do not supply transfer-to-disclosure infrastructure.|Develop a donation-specific record and mock transfer-to-disclosure case, distinguishing political money from paid services and voluntary time.
18||olympic-pilot,oceania-surge,capsules|The Olympic/surge sources and capsule proposal directly address Games-related capacity and enduring legacy.|They do not answer the stadium decision itself or imply Games approval, partnership or funding. The Olympic PDF was file/title verified only.|Add the actual venue decision/budget trail, then compare temporary capacity, retained assets and everyday use as a separate legacy question.
19||native-nations|The nation-authored agreement-repair workbench offers a concrete way to record parties, authority, obligations and proposed repair.|It does not resolve Australian treaty scope or confer cultural authority. International treaty catalogues and resource equity deals are not interchangeable with First Nations treaty policy.|Develop agreement-specific records and nation-chosen proposal layers, with domestic treaty sources still needed.
20|R15|cosmic,cosmic-pdf|Cosmic Nexus explicitly includes UAP source, hypothesis and investigation lanes.|This is an inquiry framework, not confirmation of a claim. Travel, scene rendering and a general solar-observation project do not establish disclosure evidence.|Build one observation dossier with instruments, custody, competing explanations and confidence-changing evidence.
21|R2|energy,mutual-care|Clean Energy Superpower offers a proposed generation/storage pathway relevant to mitigation. Mutual Care supplies a limited adaptation mechanism through prevention and risk sharing. Flooding is one branch within climate change.|Neither supplies a complete climate policy or measured emissions/risk reductions. Micronova is not evidence for current climate-change claims; generic solar-observation and scene projects do not fill this gap.|Keep the climate-change scope explicit; use established climate evidence for any future case and treat the flood/prevention example as a limited branch.
22||geode-ptsd|Aura Geode to Macro explicitly proposes a clinical validation phase including PTSD and multimodal sessions with biometric/research records. It is a directly relevant speculative research concept.|No validated PTSD treatment, approved clinical study, veteran/first-responder claims pathway or operating care programme is established. Its proposed research is not evidence of efficacy; generic dementia and recovery projects remain excluded.|Separate the proposed PTSD research protocol, safety/consent and clinical validation from the existing claims and continuity-of-care problem; obtain relevant specialist evidence for each.
23||music,rights,fair-go-ai|Sovereign Music supplies concrete making, rights and royalty cases. A Fair Go for the AI Age explicitly develops copyright/ICIP permissions, custodial licensing and revocable access; this supports a creator-permission record.|Neither is a complete AI-training licensing market. Generic AI trust or compute-expansion documents do not supply the missing rights mechanism.|Use a real creative workflow to compare provenance, permitted uses, human contribution, licensing and remedy.
24|||The existing P4A room has child-specific eSafety evidence; generic personal-sovereignty and AI-terms projects are not child-safety products.|No dedicated developed child-chatbot safeguard project was verified. Aura Toy is unrelated matrix UI; local hosting alone is not a child-safety mechanism.|Develop age-appropriate design, guardian/child rights, memory limits, escalation and independent testing with specialist evidence.
25|||The local room contains eSafety design and reporting sources, but mapped generic privacy/trust/legal projects do not supply a harassment remedy or moderation workflow.|No directly applicable developed reporting/moderation solution was verified.|Develop one abuse-reporting, response and appeal case with specific platform obligations and evidence-handling steps.
26|R13|queens,equality|500 Queens and Designing Equality directly address women's executive and investment decision-making pathways.|That is a bounded leadership/ownership lever, not evidence of closing the aggregate or same-job pay gap. C-Hour and generic succession ideas are not pay-equity interventions.|Separate pay rates, progression, care penalties and ownership; test the retained leadership mechanism against its specific outcomes.
27|R4|native-nations,country-deals,indigenous-deals,node|Nation-authored agreements, Country-controlled resource returns and Ready S.E.T.'s cultural/data permissions offer concrete decision-rights mechanisms.|No consent, endorsement or measured Closing the Gap outcome follows from these proposals; international treaty machinery is not a substitute.|Start with a community-chosen decision/outcome and examine whether any retained mechanism directly changes its authority, budget or data access.
28|||The room has crime/justice evidence and prevention options, but general sport, employment, housing and contribution projects were not verified as youth-justice pathways.|No directly applicable evaluated or developed youth-crime programme was identified in the mapped projects. Club activity alone is not a crime solution.|Develop a specific professional prevention/restoration pathway with victim needs, youth needs, service responsibility and measurable safety outcomes.
29|R7|ggm,housing,ggm-framework,ggm-care|The authored household framework concretely explores shared care, resources and personal autonomy as an optional way to address wanted-family barriers.|The framework is optional, not a universal answer or a new legal status. The supported-living page is a bounded local family-housing example, not national affordability policy or an operating service.|Compare the framework with conventional household cases using actual time, care, cost and autonomy assumptions.
30|R7|ggm,un-love,ggm-framework,ggm-care|Global Group Marriages and U.N. of Love are Luke's explicitly intended household/relationship thought experiments, including voice, care, repair and exit.|They do not establish current multi-person marriage recognition. General legal-reading projects add no specific agreement mechanism beyond the authored framework here.|Develop joining, shared resources, disagreement, separation and continuing responsibilities while distinguishing existing law from proposed forms.
31||legal-engine|The room has the dated proposal, costing and comparison variables. Australian Legal Engine can support retrieval of current superannuation and housing rules; general housing and succession projects do not model withdrawals or retirement balances.|No directly applicable developed super-for-housing calculator or proposal was verified beyond the P4A comparison.|Build the explicit lifetime housing/retirement and price-response model, including people without super or a deposit.
32|R3,R2,R13|mutual-futures,wealth,queens,capital,succession|Mutual succession, community ownership and women's investment influence contain concrete ways to change productive ownership; the capital calculator makes assumptions inspectable.|These are bounded ownership mechanisms, not completed redistribution or guaranteed returns. Nonmonetary contribution records are not wealth distribution.|Model financing, debt, control, wages, reserves and distributions in one ownership-transfer case.
33||legal-engine|Legal retrieval can support identifying the exact corporate-tax obligations in a defined entity/year case.|No developed multinational-tax reform or tax dataset was verified. A local-government funding submission or general reading worksheet is not a corporate-tax solution.|Build revenue, profit, tax and jurisdiction evidence first; use retrieval only to support the applicable-law check.
34|||The local room has NDIA fraud/reporting evidence. Dementia research, aged-care plans and a care venture brief do not establish service-verification or NDIS anti-fraud mechanisms.|No directly applicable developed NDIS fraud/delivery-verification project was verified.|Co-design a specific service-to-invoice verification and dispute case without turning participant records into public surveillance.
35||trust-index|The AI Trust Index Australia guide explicitly warns about AI voices, fake videos and the need to check what is real. Retain it as directly relevant scam literacy only, not a detector or recovery service.|No implemented impersonation-verification, voice-authentication, bank integration or recovery system is verified. Literacy guidance is useful but leaves these operational gaps.|Build a scam-specific independent-verification and recovery workflow before attaching any project as its implementation.
36|||The local room contains aged-care scam and complaint sources. Dementia, longevity and care-business plans do not establish anti-scam or billing-verification functions.|No directly applicable developed aged-care scam/delivery-verification solution was verified.|Develop one accessible authorised-service, delivery and invoice trail with an independent review route.
37|||The room has gambling-specific evidence and policy options. General truthfulness, wealth and legal-method projects do not implement gambling-harm measures.|No directly applicable developed gambling solution was verified.|Compare a specific advertising/product/revenue issue using gambling evidence and identify a real implementation partner.
38||mobility,legal-engine|The mobility proposal directly concerns passenger/freight travel demand; legal retrieval can support checking excise/GST provisions.|Mobility is a bounded route alternative, not a tax reform or operating autonomous service. Food/community-energy projects do not themselves model this commute or tax burden.|Compare one actual journey or freight route and its cost/tax components with the proposed service, without assuming savings.
39||legal-engine|Legal retrieval can support the dated excise-rule check; the policy comparison remains in the existing tobacco room.|No developed tobacco-tax reform or cessation programme was verified. General wellbeing/cooperative care is not a tobacco-specific intervention.|Build a dated incidence, illicit-supply and outcome comparison; keep retrieval distinct from the substantive policy gap.
40||living-twin|Living Twin explicitly models residents, housing, jobs, prices, visitors and infrastructure dependencies. It is a concrete work-in-progress local capacity simulation to inspect when designing Migration equations, not an inward-migration forecast.|No validated inward-migration/intake model is established. Twin inputs, causal assumptions and calibration need checking; the outbound Visa Atlas does not answer Australian intake settings.|Develop specific population, housing, skills and service flows with current data and time lags before choosing a tool or project.
41|R5,S1|aukus,peace,unga-transcript|The AUKUS and UNGA81 sources directly argue about strategic alternatives; the Ocean of Peace submission is a relevant source candidate for regional cooperation.|The Ocean of Peace DOCX was file/title verified only. U.N. of Love is an intended family thought experiment, not a conflict-resolution mechanism here.|Work through one actual commitment's objective, legal basis, civilian consequences, alternatives and exit; read the original peace document before importing detailed claims.
42|R5,R4,S1|aukus,eggs,node|The submissions test concentrated versus distributed capability; Ready S.E.T. offers a concrete compute dependency and recovery case. These are specific examples for examining Security fallacies.|These cases do not reduce Security fallacies to infrastructure resilience or show that decentralisation guarantees safety.|Test military, institutional and civil assumptions on their actual functions; use the retained infrastructure cases only for dependencies they address.
43|R15|cosmic,cosmic-pdf|Cosmic Nexus explicitly covers ancient-astronaut questions and provides the intended research/creative doorway.|The supporting PDF was file/title verified and does not establish alien construction. Travel, generic renderers and micronova are not evidence for ancient-alien claims.|Build one object/text dossier with chronology, context, competing explanations and evidence that could distinguish them.
44||mental-venture|The 500 Queens mental-health brief proposes a bounded non-clinical navigation pilot with maintained resources and a named owner, directly relevant to finding care.|It is not treatment or proof of shorter clinical waits. General reflection, clubs, family housing and succession projects do not supply continuity-of-care mechanisms by themselves.|Test the navigation task separately from clinical capacity and continuity, measuring access, handover and user-valued outcomes.
45||parlor,parlor-pdf|Consciousness Parlor directly develops a professional-guided psychedelic research/therapy concept.|No licensed clinic, approved protocol, efficacy or costed affordable delivery is established; the blueprint PDF was file/title verified. General cooperative wellbeing is not a funding model for this care.|Compare the concept with condition-specific clinical evidence, supervision, preparation/follow-up and actual access costs.
46|R11|law2012,legal-engine|The Relevance Ladder and cited legal retrieval are concrete supporting methods for a substance/activity-specific change-the-law case. General legal-memory worksheets add no further plant-specific mechanism.|These are legal tools, not an adopted plant policy. A medicinal-product venture or psychedelic clinic concept does not address adult cultivation rights.|Choose one substance, conduct and jurisdiction; identify exact provisions, evidence of harm and the proposed legal change.
47|||The room has actual dated holdings and Moneysmart sources. Mutual succession, community funds and general legal-reading projects do not provide super portfolio disclosure or look-through analysis.|No directly applicable developed super-holdings ingestion, exposure or member-control tool was verified.|Build a statement-to-holdings case from the actual fund files, issuer disclosures, fees, votes and member choices.
48||unga-transcript,legal-engine|The UNGA81 transcript directly proposes truthfulness/correction mechanisms; legal retrieval can support a precise comparison of electoral rules. The existing local Aura Politics link remains relevant to Luke's authored candidate-mirror thought experiment.|No truth tribunal or automatic classifier is established. AI Trust Index branding and generic legal-reading material do not supply political-ad adjudication.|Develop one ad's claim, evidence, response and correction record, distinguishing funding disclosure, opinion, satire, error and deliberate deception.'''

def prune_map(data,link):
 original=copy.deepcopy(data)
 history=OUT/'archive/solution-associations-before-pruning-2026-10-03.json'
 history.parent.mkdir(parents=True,exist_ok=True)
 if not history.exists():history.write_text(json.dumps(original,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 decisions={}
 for line in DECISIONS.splitlines():
  n,local,cross,fit,gap,nextwork=line.split('|')
  decisions[int(n)]={'local':local.split(',') if local else [],'cross':cross.split(',') if cross else [],'fit':fit,'gap':gap,'next':nextwork}
 assert len(decisions)==48
 research=data['crossRepositoryResearch'];all_sources=research['sources'];audit=[]
 all_sources['geode-ptsd']={'title':'Aura Geode architecture and proposed PTSD clinical research','url':'https://github.com/auraofintelligence/multi-site-Minjerribah-network/blob/main/source-documents/aura-geode-to-macro.md','repository':'https://github.com/auraofintelligence/multi-site-Minjerribah-network','status':'Original Markdown read on 3 October 2026: explicitly proposes clinical validation including PTSD and multimodal/biometric research. Speculative design, not validated care or an approved trial.'}

 # A shared destination's external links are not automatically evidence for every gripe.
 primary_filters={1:[],6:[],7:['health.gov.au/topics/medicare/'],9:[],15:[],16:[],17:[],18:[],19:[],20:['science.nasa.gov/uap/','naa.gov.au/'],21:['bom.gov.au/water/floods/'],22:[],48:['aec.gov.au/']}
 for row in data['topics']:
  n=row['number'];d=decisions[n];old=copy.deepcopy(row)
  row['relatedReferences']=d['local']
  row['adjacentLocalTools']=[t for t in old['adjacentLocalTools'] if n==11 and 'sensorium-place-pack' in t['path']]
  row['existingSubstanceAndStatus']=d['fit'];row['potentialSolutions']=d['fit'];row['obviousGap']=d['gap'];row['potentialNextWork']=d['next']
  row['crossRepositoryAdditions']={'sourceKeys':d['cross'],'additionalSubstance':d['fit'],'stageAndGap':d['gap'],'proposedNextWork':d['next']}
  primary=[];removed_embedded=[]
  for a in old['sourcesAlreadyLinkedInRoom']:
   # Project links are assessed in the explicit retained lists, not smuggled back as evidence.
   own='auraofintelligence' in a['href']
   relevant=not own and (n not in primary_filters or any(s in a['href'] for s in primary_filters[n]))
   (primary if relevant else removed_embedded).append(a)
  row['sourcesAlreadyLinkedInRoom']=primary
  removed_local=[k for k in old['relatedReferences'] if k not in d['local']]
  removed_cross=[k for k in old['crossRepositoryAdditions']['sourceKeys'] if k not in d['cross']]
  removed_details=[]
  for kind,keys,registry in [('local',removed_local,original['references']),('cross-repository',removed_cross,all_sources)]:
   for key in keys:
    src=registry[key]
    removed_details.append({'kind':kind,'key':key,'title':src['title'],'urlOrPath':src.get('url',src.get('urlOrPath')),'reason':SPECIFIC_REMOVAL_REASONS.get((n,key),'No additional gripe-specific mechanism is established by this connection in the reviewed material. '+d['gap'])})
  if n==48:row['relatedLocalPages']=[{'path':'pages/aura-politics.html','status':'Authored candidate-mirror thought experiment; not an operating tribunal.'}]
  row['associationAssessment']={'directFit':d['fit'],'remainingGap':d['gap'],'noDevelopedProjectVerified':not d['local'] and not d['cross'],'scope':'Association review only; existing visitor content has not been changed.'}
  audit.append({'number':n,'topic':row['topic'],'retainedLocalReferences':d['local'],'retainedCrossRepositorySources':d['cross'],'removedLocalReferences':removed_local,'removedCrossRepositorySources':removed_cross,'removedDetails':removed_details,'removedGenericTools':[t for t in old['adjacentLocalTools'] if t not in row['adjacentLocalTools']],'removedEmbeddedProjectOrOffTopicLinks':removed_embedded,'retainedRationale':d['fit'],'removedRationale':d['gap'],'remainingGap':d['gap']})
 used_local={k for x in data['topics'] for k in x['relatedReferences']};used_cross={k for x in data['topics'] for k in x['crossRepositoryAdditions']['sourceKeys']}
 data['references']={k:v for k,v in data['references'].items() if k in used_local}
 research['sources']={k:v for k,v in all_sources.items() if k in used_cross}
 research['sources']['trust-index']['applicableSupportingPage']='https://auraofintelligence.github.io/strange-but-true-ai-trust-index/australia.html'
 research['topics']={str(x['number']):copy.deepcopy(x['crossRepositoryAdditions']) for x in data['topics']}
 data['associationReview']={'date':'2026-10-03','rule':'Retain a direct gripe connection or a concrete applicable mechanism, evidence source or tool; shared branding and broad themes are insufficient.','history':'docs/planning/archive/solution-associations-before-pruning-2026-10-03.json','all48RowsReviewed':True,'rowsWithNoDevelopedProjectVerified':[x['number'] for x in data['topics'] if x['associationAssessment']['noDevelopedProjectVerified']]}
 review={'date':'2026-10-03','rowsChanged':[x['number'] for x in audit],'rowsWithNoDevelopedProjectVerified':data['associationReview']['rowsWithNoDevelopedProjectVerified'],'supportingToolOnlyRows':[10,16,17,31,33,39,46],'removedLocalReferenceAssociations':sum(len(x['removedLocalReferences']) for x in audit),'removedCrossRepositoryAssociations':sum(len(x['removedCrossRepositorySources']) for x in audit),'removedGenericToolAssociations':sum(len(x['removedGenericTools']) for x in audit),'retainedCrossRepositorySources':len(used_cross),'sourceChecks':'docs/planning/association-source-checks-2026-10-03.json','reconciliationSourceChecks':'docs/planning/association-reconciliation-source-checks-2026-10-03.json','reportReconciliation':'docs/planning/association-report-reconciliation-2026-10-03.md','rows':audit}
 (OUT/'association-fit-review-2026-10-03.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 review_lines=['# Association pruning: exact changes and rationale','','All 48 rows were reviewed and changed. Approved comic copy, topics and destinations remain unchanged. No visitor content was rewritten.','','This is a fit test, not an operational-only test: relevant proposals, thought experiments and source candidates remain labelled honestly. No project was deleted. The complete previous mapping is retained in '+link('the history snapshot','docs/planning/archive/solution-associations-before-pruning-2026-10-03.json')+'.','','Removed association edges: '+str(review['removedLocalReferenceAssociations'])+' local references, '+str(review['removedCrossRepositoryAssociations'])+' cross-repository references and '+str(review['removedGenericToolAssociations'])+' generic tool placements. These are placements across rows, not deleted repositories.','','No directly applicable developed project verified: '+', '.join(map(str,review['rowsWithNoDevelopedProjectVerified']))+'. Supporting-tool-only rows: 10, 16, 17, 31, 33, 39, 46; their substantive policy gaps remain.','','The '+link('actual source-check record','docs/planning/association-source-checks-2026-10-03.json')+' contains public pages, the Matrix README, AI starter guide and the original clinical/aged-care documents read for the disputed fits. Other sources retain the supplied researcher’s status; file/title-only sources have not been promoted to full-content evidence.','']
 review_lines+=['The '+link('report reconciliation','docs/planning/association-report-reconciliation-2026-10-03.md')+' records the final direct-source exceptions and the additional GP-affordability gap; '+link('reconciliation source checks','docs/planning/association-reconciliation-source-checks-2026-10-03.json')+' preserves the exact source material checked.','']
 for item in audit:
  review_lines+=['## '+str(item['number']).zfill(2)+'. '+item['topic'],'','**Retained rationale:** '+item['retainedRationale'],'','**Remaining gap:** '+item['remainingGap'],'']
  for removed in item['removedDetails']:review_lines+=['- Removed '+link(removed['title'],removed['urlOrPath'])+' (`'+removed['kind']+':'+removed['key']+'`): '+removed['reason']]
  if item['removedGenericTools']:review_lines+=['- Removed generic draft builders: '+', '.join(t['path'] for t in item['removedGenericTools'])+'. An editable draft format does not supply the missing topic-specific implementation.']
  if item['removedEmbeddedProjectOrOffTopicLinks']:review_lines+=['- Removed embedded project/off-topic room links from this row’s evidence list: '+ '; '.join(link(t['label'],t['href']) for t in item['removedEmbeddedProjectOrOffTopicLinks'])+'. Shared room membership is not relevance; directly retained project links are listed separately in the main map.']
  review_lines+=['']
 (OUT/'association-fit-review-2026-10-03.md').write_text('\n'.join(review_lines),encoding='utf-8')
 lines=['# Twinkle gripes and directly relevant solution work','','Planning map · 3 October 2026 · association review after `6b59960`','','All 48 approved gripes and destinations are retained. Project connections below require a direct subject match or a concrete applicable mechanism, evidence source or tool. A useful legal lookup tool is labelled as support, not presented as a developed tax, gambling or care policy. No visitor pages were changed by this review.','','## What remains useful','','- Retain the explicit **Marriage/divorce → Global Group Marriages / U.N. of Love** and **Sensorium → UNGA81 / Ready S.E.T.** connections, with their actual proposal/tool status.','- Use clear mechanisms: Shared Table and food-waste records for food; mutual reserves for insurance; succession/capital tools for workforce and ownership; creator rights records for copyright; a named non-clinical navigation pilot for finding mental-health support.','- Leave a gap where the reviewed material does not supply a specific solution. Do not attach C-Hour, Aura, GAJRA or generic legal projects to fill a row.','- **Climate change is not micronova.** Retained clean-energy proposals address mitigation and mutual care addresses adaptation/prevention and risk sharing; neither supplies a full climate policy.','- **Multi-site Minjerribah** remains the actual local collaboration Luke was invited into with Indigenous people on Straddie, used only for directly relevant supported-living/safe-place examples. No national framework, public mandate, completed implementation or wider endorsement is inferred. The separate housing-policy source remains unidentified.','','## Housing as the depth benchmark','','The existing '+link('Housing Simulations room','pages/housing-simulations.html')+' combines evidence, different tenure/ownership pathways, repairs, local delivery and long-term questions. It is a static workbench, not a working housing calculator. The map retains specific supported-living, capsule and housing-capacity simulation connections with their limits; generic food or contribution projects are not housing mechanisms merely because the room mentions them.','','## Gaps to leave visible','','No directly applicable developed project was verified for topics **'+', '.join(str(n).zfill(2) for n in review['rowsWithNoDevelopedProjectVerified'])+'**. Their current rooms may contain useful primary evidence and options; that is different from having an applicable project solution. Legal-retrieval-only rows also retain an explicit substantive-policy gap.','','## All 48 gripes','','| # | Plain topic | Approved comic headline | Current room |','|---|---|---|---|']
 for x in data['topics']:lines.append('| '+str(x['number']).zfill(2)+' | '+x['topic']+' | '+link(x['headline'],'pages/twinkle-'+x['slug']+'.html')+' | '+link(x['destination'],x['currentRoom'])+' |')
 lines+=['','## Specific fit, limits and next work','']
 for x in data['topics']:
  lines+=['### '+str(x['number']).zfill(2)+'. '+x['topic'],'','**Comic headline:** '+x['headline'],'','> '+x['gripe'],'','**Current room:** '+link(x['destination'],x['currentRoom']), '','**Relevant material / mechanism:** '+x['existingSubstanceAndStatus'],'','**Gap and limits:** '+x['obviousGap'],'','**Next work:** '+x['potentialNextWork'],'']
  refs=[link(data['references'][k]['title'],data['references'][k]['urlOrPath']) for k in x['relatedReferences']]
  refs += [link(research['sources'][k]['title'],research['sources'][k]['url']) for k in x['crossRepositoryAdditions']['sourceKeys']]
  if refs:lines+=['**Retained project/document links:** '+'; '.join(dict.fromkeys(refs))+'.','']
  else:lines+=['**Project link:** none retained; no directly applicable developed solution verified.','']
  for t in x['adjacentLocalTools']:lines+=['**Specific local tool:** '+link(t['description'],t['path'])+'.','']
  if x['sourcesAlreadyLinkedInRoom']:lines+=['**Relevant external evidence already linked by the room:** '+'; '.join(link(a['label'],a['href']) for a in x['sourcesAlreadyLinkedInRoom'])+'.','']
  if x['number']==48:lines+=['**Explicit local authored connection:** '+link('Aura Politics - candidate-mirror thought experiment','pages/aura-politics.html')+'.','']
 lines+=['## Retained source status','','These are the retained sources, not an endorsement of every claim they contain. External tool status is attributed to the supplied researcher unless a local test is identified. A PDF/DOCX verified only by file/title remains a source candidate, not full-content evidence.','']
 for k,x in data['references'].items():lines+=['- **'+k+' - '+link(x['title'],x['urlOrPath'])+'**. '+x['status']]
 for k,x in research['sources'].items():lines+=['- **'+k+' - '+link(x['title'],x['url'])+'** · '+link('Repository',x['repository'])+'. '+x['status']+'.']
 lines+=['','## Removed associations and preserved history','','The '+link('readable row-by-row fit review','docs/planning/association-fit-review-2026-10-03.md')+' and '+link('structured review','docs/planning/association-fit-review-2026-10-03.json')+' record every retained and removed key, tool and embedded link with rationale. All 48 rows changed in this relevance pass. The '+link('pre-pruning map and full source registry','docs/planning/archive/solution-associations-before-pruning-2026-10-03.json')+' preserves the earlier research and descriptions; projects and source documents have not been deleted. The separate '+link('cross-repository evidence file','docs/planning/cross-repo-evidence-2026-10-03.json')+' remains an attributed research catalogue, not a claim that every catalogue entry belongs in a solution row.','','Historical/current C-Hour versions remain distinct: current C-Hour is nonmonetary; earlier token/redemption language is history. No C-Hour association is retained simply to make a topic look solved. The verified local builder results remain in '+link('the local tool audit','docs/planning/local-builder-audit-2026-10-03.json')+'; generic draft exporters were removed from rows where they did not answer the specific problem.','','Primary sources already in a room have been screened for topic fit, especially where several gripes share one room. Current law, figures, costs and outcomes still require source checking when an actual policy case is developed. This cleanup does not change the published rooms, the original ticker, any joke or any repository outside this planning work.','']
 return data,lines
