"""One-time migration of the existing Sensorium into reviewed room sources."""
from pathlib import Path
R=Path(__file__).resolve().parents[1]
p=R/'pages/web3-sensorium.html'
s=p.read_text(encoding='utf-8')
base='https://auraofintelligence.github.io/ready-set-co-op-cultural-intelligence-node/'
def link(path,label):return f'<a href="{base}{path}" target="_blank" rel="noopener noreferrer">{label}</a>'
def panel(id,title,body):return f'<div class="feature-panel" id="{id}"><p class="eyebrow">Community intelligence · October 2026</p><h2>{title}</h2>{body}</div>\n'
insert=panel('missing-middle','Serious compute. A local say.', '''<p>Between a phone and a hyperscale centre sits missing middle: serious computing controlled by towns, islands, libraries, universities, hospitals, cooperatives and communities. A school can learn on real equipment; a hospital can keep protected workloads close; filmmakers can render; researchers can model reefs, farms and public infrastructure. The machine follows the purpose.</p><p>That gives the Sensorium somewhere to live: local models, maps, legal memory and simulations held by people who can inspect, maintain and change the system. Sovereignty means custody, keys, skills, recovery and the ability to leave a provider, as well as where the machine sits.</p><div class="source-links"><a href="https://auraofintelligence.github.io/UNGA81-Luke-Hayes/capability.html#the-missing-middle-of-ai" target="_blank" rel="noopener noreferrer">UNGA81 missing-middle argument</a><a href="https://github.com/auraofintelligence/ready-set-co-op-cultural-intelligence-node/blob/main/supporting-documents/senate-ai-and-data-centres-submission-2026.md" target="_blank" rel="noopener noreferrer">24 August 2026 Senate submission</a></div>''')
insert+=panel('compute-continuum','One connected continuum. Different jobs.', '''<div class="clue-grid"><div class="clue"><strong>Personal / household</strong><span>Private AI, personal memory, keys and permissions on devices people control.</span></div><div class="clue"><strong>Edge / neighbourhood</strong><span>Sensors, local communications, disaster kiosks and fast nearby services.</span></div><div class="clue"><strong>Community missing middle</strong><span>Serious shared racks or clusters for larger models, simulation, rendering, training and public access.</span></div><div class="clue"><strong>State / national</strong><span>Research, public-interest workloads, evaluation, coordination and sovereign backup.</span></div><div class="clue"><strong>Hyperscale</strong><span>Frontier training and elastic capacity, with portable workloads and meaningful provider choice.</span></div><div class="clue"><strong>Specialised horizons</strong><span>Quantum and possible future orbital systems, connected through chosen interfaces. These are distinct capabilities, not a delivered local service.</span></div></div><p>This continuum comes from Senate proposal, which explicitly calls for interoperability and permissions standards like the Web3 global sensorium proposal. It does not rank people or require every workload to travel upwards.</p><div class="source-links"><a href="https://auraofintelligence.github.io/p4a-oceania-cinema/pages/compute.html" target="_blank" rel="noopener noreferrer">P4A Oceania compute tiers</a></div><p>Straddie’s L0-L2 labels describe scene briefs: private spaces, local places and bioregions. They are not these compute tiers. A bioregional scene brief can be written on a laptop; the chosen rendering job may need a different machine.</p>''')
insert+=panel('ready-set-node','Ready S.E.T.: the node around the rack.', '<p>The Dunwich cultural intelligence node is a public working proposal. GB200 NVL72 supplies a concrete rack-scale reference, replaceable across vendors and generations. It is not evidence that a rack has been bought, installed or commissioned. Real workloads, a site pathway, power, liquid cooling, fire protection, secure networking, maintenance and lifecycle costs must determine the build.</p><div class="trust-flow"><article><span>Equipment + people</span><strong>A machine people can use and maintain</strong><p>Secure infrastructure sits alongside a visible workshop, paid operators, creators, learners and technical support.</p></article><article><span>Custody + applications</span><strong>Permission stays attached</strong><p>Viewing, storage, transcription, model work, publication and review are separate choices. Technical administration does not grant cultural authority.</p></article><article><span>Chosen bridges</span><strong>Share selected work</strong><p>A connection names its cargo: a public method, selected output, benchmark, tool or learning exchange. Local identity and custody remain visible.</p></article></div><div class="source-links">'+link('node.html','Explore the rack and its layers')+link('culture.html','Cultural relationships and permissions')+link('cooperative.html','Co-op work, learning and equipment')+link('network.html','Chosen network connections')+'</div>')
insert+=panel('working-tools','Use the public tools now.', '<p>The proposed compute node builds around work that already has public doors. The local brief builder runs in the browser tab and exports Markdown. The model workbench traces a selected question through sources, proposed rack work, outputs and human review. Neither requires pretending the physical rack is operational.</p><div class="source-links">'+link('process.html#plan-builder','Build and download a local node brief')+link('digital-twin.html#model-workbench','Explore modelling workloads')+link('uses.html','Choose an everyday workload')+link('projects.html','Open the project catalogue')+'</div><p>The catalogue distinguishes the working Quandamooka Country Events Engine, the Gumpi ferry evidence prototype, the public citation-first Australian Legal Engine and Straddie scene builders from proposed screen networks, place projects and rack workloads. Follow each project’s own status and source trail.</p><p>Start with one question: what service should stay available when the island loses its outside connection? Record the people responsible, minimum map or directory, permissions, power and cooling budget, recovery exercise and what may be shared afterwards.</p><div class="source-links"><a href="https://github.com/auraofintelligence/ready-set-co-op-cultural-intelligence-node" target="_blank" rel="noopener noreferrer">Ready S.E.T. source repository</a><a href="p4a-builder.html?tool=sensorium-place-pack">P4A Sensorium place pack</a></div>')
insert+=panel('public-choices','Build a pilot people can judge.', '<p>Senate submission proposes a varied early-adopter network, public learning, open operating playbooks and published failures as well as successes. Its A$6 million all-in frontier-node allowance and approximately A$600 million for 100 sites are planning allowances, not vendor quotes or an approved budget. Smaller and reused equipment remain live choices.</p><div class="clue-grid"><div class="clue"><strong>Local rack</strong><span>More local control and practical learning, with demanding maintenance, power, cooling and utilisation responsibilities.</span></div><div class="clue"><strong>Shared regional capacity</strong><span>Pool scarce skills and equipment across hosts, while testing who gets access and what survives a network outage.</span></div><div class="clue"><strong>Personal + cloud first</strong><span>Lower initial local capital needs, but service dependency, recurring fees and exit costs must be visible.</span></div></div><p>Ask a library, university, hospital, council or cooperative to host a workload workshop. Use the node brief to name daily uses, paid roles, cultural permission, procurement alternatives and a stop-or-expand review. Publish measured utilisation, energy, cooling and water use, recovery results and community outcomes. Heat reuse needs an actual nearby heat demand and engineering; distribution alone does not erase resource impacts.</p><div class="source-links">'+link('process.html','Seven movements from listening to review')+'<a href="civic-ledger.html">Record the public receipt</a><a href="sovereignty-stack.html">Test custody and exit</a></div>')
s=s.replace('          <div class="feature-panel">\n            <p class="eyebrow">Core pattern</p>',insert+'          <div class="feature-panel">\n            <p class="eyebrow">Core pattern</p>')
s=s.replace('local and boring on purpose','grounded in everyday needs').replace('The cosmic version can come later; the public trust layer has to work on the ground first.','The same source trails can support larger scientific questions while communities retain control of what they share.')
s=s.replace('<strong>2026-05-09, Australia/Brisbane.</strong> Drafted from the P4A planning note <em>Web3 Sensorium for Science Debate</em>. Current status: concept architecture, not adopted policy, legal advice, scientific validation or a live platform.','<strong>3 October 2026.</strong> Updated against UNGA81 capability page, Ready S.E.T. public pages and 24 August Senate submission. Sensorium architecture and the physical node remain proposals; the linked brief builders and public project tools have their own working status. These options are open for public consideration, not adopted party policy.')
(R/'content/rooms').mkdir(exist_ok=True)
(R/'content/rooms/web3-sensorium.html').write_text(s,encoding='utf-8')
