from html import escape as e
def facts(r,data):
 src=data['sources'][r['kind']];p=r['sourceProperties'];out=[f'<div data-first-peoples-facts><span class="vic-kicker">First Peoples · {e(r["body"])}</span><h2>{e(r["fullName"])}</h2>']
 out.append(f'<p class="vic-data-note">{e(data["interpretation"])}</p><dl class="vic-component-list"><div><dt>Record authority</dt><dd>{e(src["authority"])}</dd></div><div><dt>Retrieved</dt><dd>{e(data["retrieved"])}</dd></div><div><dt>Catalogue metadata updated</dt><dd>{e(src["catalogueMetadataUpdated"])}</dd></div>')
 for k,v in r['dates'].items():out.append(f'<div><dt>{e({"reg_date":"Source registration date","date_commenced":"Agreement commencement","version_date":"Source feature version"}[k])}</dt><dd>{e(v or "Not supplied")}</dd></div>')
 out.append('</dl>')
 if r['kind']=='rap':out.append('<p>RAPs have appointed cultural-heritage functions under the Victorian Aboriginal Heritage Act 2006. This is not a complete Country, language, native-title or land-ownership map. More than one RAP can be registered for the same area. Source registration dates are not dates of cultural connection or proof of the latest boundary revision.</p>')
 else:out.append(f'<p>This polygon records a Recognition and Settlement Agreement extent. Source legislation: <strong>{e(p["legislation"])}</strong>. Agreement provisions and parcel-specific rights must be checked in the agreement; the polygon alone does not establish identical rights throughout its extent.</p><p>Source official area: {p["official_area_ha"]:,.2f} hectares. This published field is not recalculated from the displayed projection.</p>')
 out.append(f'<p><a href="{e(r["officialProfile"])}">Official organisation / agreement information</a> · <a href="{e(src["catalogue"])}">Boundary catalogue and licence</a> · <a href="{e(src["url"])}">Exact source query</a></p><p class="vic-quiet">Raw source attributes are preserved in the downloaded geometry. Contact fields in that source are not represented as freshly verified current contacts; use the official organisation page. Geometry is the un-generalised EPSG:4326 service response, with original numeric values retained. No sensitive heritage-site layer was accessed.</p>')
 out.append('<h3>Country, language and community-led knowledge</h3><ul>')
 for item in data['communitySources']:out.append(f'<li><a href="{e(item["url"])}">{e(item["name"])}</a> — {e(item["note"])}</li>')
 out.append(f'</ul><p><a href="{e(data["overlapPolicySource"])}">Why multiple RAP records can apply to one area</a> · <a href="https://www.nntt.gov.au/assistance/geospatial/spatial-data">National Native Title Tribunal: separately defined claims, determinations and agreements</a></p><p class="vic-quiet">Native-title geometry is not imported in this view. Community cultural maps are linked, not reproduced or traced; no bulk reuse permission has been assumed. {e(data["directoryNote"])}</p><p>Attribution: © State of Victoria, {e(src["authority"])}. <a href="{e(src["licenceUrl"])}">CC BY 4.0</a>. Display projection and lossless delivery encoding applied; source coordinates and fields unchanged.</p></div>')
 return ''.join(out)
